### ISSUE TITLE
Update Better Discord Plugin

### ISSUE THREAD

**Issue by Aytackydln** [Aurora-RGB/Aurora#10]
[AuroraGSI.plugin.zip](https://github.com/Aurora-RGB/Aurora/files/7869078/AuroraGSI.plugin.zip)

**Comment by snappyapple632** [comment]
I know Aurora is meant to be in EOL, but would it be possible to port this plugin to Powercord or at least make it work with their bdCompat plugin? It seems to be the most dominant desktop client mod for Discord right now, and the plugin as it stands doesn't work with bdCompat.

**Comment by Aytackydln** [comment]
I actually don't know anything about this plugin. I got this file on Aurora's discord. But it might be debuggable with Powercord bdCompat then it is possible to make them compatible.
