### ISSUE TITLE
Razer device manager - NullPointerException

### ISSUE THREAD

**Issue by mamang126** [Aurora-RGB/Aurora#100]
### Expected Behaviour
Razer device manager should have started but it never starts

### Actual Behaviour
The program runs as normaly do but when I go to Configuration/DeviceManager  the start button is enabled in Razer row

### Reproduction steps
Install Aurora from binary. Without any Razer software installed.
Go to Configuration/Device&Wrappers/Razer and install Chroma.
Restart PC

### Frequency
Every time. I have tested a lot of times restarting the PC.

### Aurora Version:
beta v0.8.1

### Previously an Issue?
Don't know. I have tested in other computer with the same keyboard and it works great

### LOGS
```
[ERROR] 18:16:36: Razer device, Exception! Message:System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en System.Object.GetType()
   en Corale.Colore.Core.RegistryHelper.IsSdkAvailable()
   en Aurora.Devices.Razer.RazerDevice.Initialize() en C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:línea 60
[INFO] 18:16:36: Device, Razer, was not initialized
```

**Comment by Aytackydln** [comment]
https://github.com/Aurora-RGB/Aurora/releases

beta v0.8.1 is a very old version. You should update :)

**Comment by mamang126** [comment]
Perfect. Now its working. I asume thats i was updated cause update tool said that.
Thanks @Aytackydln
