### ISSUE TITLE
Aurora crashes after clicking any RGB.NET device

### ISSUE THREAD

**Issue by joaocaparroz** [Aurora-RGB/Aurora#101]
### Expected Behaviour
Aurora not crashing

### Actual Behaviour
Aurora crashing

### Reproduction steps
Aurora crashes after clicking any device on the "Configure RGB.NET Devices"

### Frequency
Every time

### Aurora Version:
v81

### Previously an Issue?
No

![image](https://user-images.githubusercontent.com/19500222/202799998-6fe937ce-a398-4f77-a83f-78e8c85517f7.png)

**Comment by Aytackydln** [comment]
This might be a one time problem, can you delete %appdata%/aurora/AsusDevices.json file? I will fix this permanently next release

**Comment by joaocaparroz** [comment]
The problem persists after deleting the file.
The AsusDevices.json it recreated after I click any of the buttons (like "[LedStripe] Asus AddressableStrip1") and an entry for the device is added to the json file.

json file contents:
```
{
  "d": [
    {
      "n": "Asus ROG MAXIMUS XI HERO (WI-FI)",
      "k": null
    },
    {
      "n": "Asus Vga 1",
      "k": null
    }
  ]
}
```

**Comment by Aytackydln** [comment]
Alright, I've fixed and tested with clear data. If you solved it with editing the json manually, rename AsusDevices.json to DeviceMappings.json.

Build will be done in 10 minutes

**Comment by joaocaparroz** [comment]
Worked like a charm in v82. Thanks, you are awesome!
