### ISSUE TITLE
Shutdown: failed to dispose of RazerManager

### ISSUE THREAD

**Issue by ENDrain** [Aurora-RGB/Aurora#110]
Here's a log for a shutdown error in Aurora v96 release. This is a known problem so forgive me for not filing a proper bug report. In this instance RazerManager is failed to dispose of.

[2022-12-14 15.48.15.log](https://github.com/Aurora-RGB/Aurora/files/10228002/2022-12-14.15.48.15.log)

**Comment by Aytackydln** [comment]
Thanks, it is possible that some leftover dlls stayed after updates. I didn't have to identify and make a cleanup scripts for new updates
