### ISSUE TITLE
Overwatch effects not working

### ISSUE THREAD

**Issue by ENDrain** [Aurora-RGB/Aurora#111]
### Expected Behaviour
Overwatch effects tab displaying appropriate effects when the game is running.

### Actual Behaviour
Overwatch effects tab is black when the game is running AND Razer devices are active in Device Manager. Once Razer is disabled in Device Manager, Overwatch tab ligths up.

### Reproduction steps
1. Run Aurora.
2. Run Overwatch. This step and the previous one can be executed in any order.
3. Open Overwatch tab in Aurora.
You will see that the device preview is dark.
4. Go to Arurora Settings, Device Manager tab, and stop Razer devices. Open Overwatch tab again.
You will see that the device preview is lit up with effects from the game.
5. Go to Aurora Settings, Device Manager tab, and run Razer devices back again. Open Overwatch tab again.
You will see that the device preview is dark.

### Frequency
Every time

### Aurora Version:
v96

### Previously an Issue?
Don't know

### Additional comments

Devices are working as intended in Desktop profile.

[2022-12-14 19.04.36.log](https://github.com/Aurora-RGB/Aurora/files/10229891/2022-12-14.19.04.36.log)

**Comment by Aytackydln** [comment]
Can you tell me the chroma sdk version in Devices & Wrappers tab?

**Comment by Aytackydln** [comment]
The problem is on chroma sdk. When did you install it? People have been complaining about it for 2 weeks (people that started using new) but yesterday someone got it working on first try. Can you reinstall chroma?

**Comment by ENDrain** [comment]
Yesterday, just started using. Already have, maybe will try some more

**Comment by ENDrain** [comment]
Can you give instructions on how to obtain an older SDK version?

**Comment by Aytackydln** [comment]
https://cdn.razersynapse.com/1661759489M35DwFzqRazerChromaBroadcasterSetup_v3.7.0831.082915.exe

this is an older one. Uninstall chroma from Auroa first

**Comment by Aytackydln** [comment]
did you solve your problem?

**Comment by ENDrain** [comment]
The problem wasn't concerned with Razer SDK. I had to reorder connected apps in Synapse and out Overwatch on top. When Overwatch is on top, Aurora can capture OW SDK messages and pass them on to keyboard and peripherals
