### ISSUE TITLE
Aurora not working with Corsair K100 above V95

### ISSUE THREAD

**Issue by MLConian** [Aurora-RGB/Aurora#114]
### Expected Behaviour
Lighting profiles should work on desktop and in-game.

### Actual Behaviour
Lighting does not change from the default setting in iCue. Initializing Corsair devices from Device Manager in Aurora results in a fatal error, and causes Aurora to crash.

### Reproduction steps
- Set lighting profile in iCue 4.31.168.
- Start Aurora. Neither desktop mode or gaming profiles work in preview, nor do gaming profiles work in-game. Whether Aurora is started before or after iCue does not matter.

### Frequency
Always.

### Aurora Version:
V102.

### Previously an Issue?
Yes, although it was not an issue when I ran V65 until this morning. After removing V102 and going back to V84 (the version I thought I had been running), however, the issue persists.

**Comment by MLConian** [comment]
I got it to work again, briefly, by installing older versions of Aurora. Because the desktop profile is automatically enabled, you can immediately check whether Aurora is doing anything at all, and installing anything newer than V95 showed only non-responsive RGB. However, running V95 or below does work with the desktop profile the first time around, turning off the desktop seems to disable all communication with connected devices permanently. Even restarting the pc does not help, it only works the one time and only as long as you don't turn off the desktop profile. Before, I saw my K100 in the device manager, but now it doesn't show up anymore and restarting the Corsair service from Aurora briefly shows the device connected, before it goes back to "not initialized".

**Comment by Shadowex3** [comment]
Seems tied to icue. I have aurora v102 with icue v4.30.162 and everything works fine aside from occasionally randomly needing to restart the k100 device in Aurora.

**Comment by Aytackydln** [comment]
can you try with latest icue version? from what I've seen from developers of rgb.net, it seems 4.32 is the minimum required icue for the sdk
