### ISSUE TITLE
Keycap types with backglow cause extreme lag

### ISSUE THREAD

**Issue by Shadowex3** [Aurora-RGB/Aurora#115]
### Expected Behaviour
App responsiveness and framerate should be unaffected

### Actual Behaviour
Choosing either "Default (with backglow)" or "Backglow only" options for keycaps results in the entire app lagging badly. As a rough benchmark it takes about 2 full seconds from clicking the dropdown arrow to the menu opening again to select something else. Other options show **G**PU usage bouncing around 20-30% usage, erring towards the low end, while the "with backglow" options peg it at 30% minimum with frequent spikes to 40%.

### Reproduction steps
Under "Devices & Wrappers" select one of the keycap types with "backglow".

### Frequency
Every time

### Aurora Version:
v102

### Previously an Issue?
No idea, never attempted before        

### Machine specs in case this is system dependent
Ryzen 5 5600x
32gb DDR4 with D/EOCP enabled (AMD XMP equivalent)
MSI 6800XT 
AMD first-party 22.11.2 WHQL drivers, full DDU clean install

**Comment by Aytackydln** [comment]
20-30% usage with other options are still a bad thing. What is the cpu usage while UI is closed?

**Comment by Shadowex3** [comment]
GPU usage, sorry, I had a mental typo and my brain went for "C" instead of "G". CPU usage for aurora is consistently negligible under all circumstances I've run into so far.

**Comment by Aytackydln** [comment]
UI performance is least of my priorities right now. Just usability is enough for me. If it lags so much that it is not usable I will have a look

**Comment by Shadowex3** [comment]
I wouldn't have opened a ticket otherwise. I wasn't exaggerating when I said two seconds, I checked with a stopwatch and the entire program lagged so severely that just opening the dropdown to change the keycap type back to "Default" or "Colorized" took 2 full seconds from click to the dropdown appearing. At least on my machine choosing any keycap style with "Backglow" leads to the program lagging so badly it's unusable, taking several seconds to respond to any action or click.

**Comment by Aytackydln** [comment]
Fixed with last version: https://github.com/Aurora-RGB/Aurora/releases/tag/v110
