### ISSUE TITLE
Ambilight's "flip image" option not working.

### ISSUE THREAD

**Issue by Ahegao** [Aurora-RGB/Aurora#116]
### Expected Behaviour

The image should be flipped vertically and appear as a reflection of the screen. 
### Actual Behaviour

The image on keyboard remains the same when "flip Image" is enabled. Nothing happens.
### Reproduction steps

1. Setup an Ambilight layer.
2. Activate the "flip image" option.
3. Observe how the lights on keyboard remain the same without being flipped vertically.

### Frequency

5/5 ratio. Always present.
### Aurora Version:

v102
### Previously an Issue?

Don't Know

**Comment by Aytackydln** [comment]
Fixed with last version

https://github.com/Aurora-RGB/Aurora/releases/tag/v104
