### ISSUE TITLE
Wooting 60HE RGB SDK support added

### ISSUE THREAD

**Issue by Tyrasuki** [Aurora-RGB/Aurora#117]
Please add support for the following device:

**Device Name:**  Wooting 60HE

**Device Website:**  https://next.wooting.io/wooting-60he

Unfortunately this isn't as simple as last time ([#2340](https://github.com/antonpup/Aurora/pull/2340)), where you could just update the RGB SDK.
Seems new hooks will have to be used.

Latest SDK with (supposedly) full support for the Wooting 60HE has been released yesterday (2022-01-04):
https://github.com/WootingKb/wooting-rgb-sdk/releases

I'm also open to test dev builds for this, as I have a 60HE I'm typing this with. :)

**Comment by Aytackydln** [comment]
Hey, this issue is on my radar but I'm focusing on other bugfixes right now. Just wanted to give an update

**Comment by Aytackydln** [comment]
Should be usable with (rgb.net) implementation in Aurora
