### ISSUE TITLE
Crash when running foobar2000

### ISSUE THREAD

**Issue by Shadowex3** [Aurora-RGB/Aurora#118]
### Expected Behaviour
Aurora works like normal

### Actual Behaviour
Aurora crashes

### Reproduction steps
Install foobar2000 v1.6.14 and then try to run it and aurora at the same time

### Frequency
Every time I open foobar2000, or try to start aurora while foobar2000 is open

### Aurora Version:
V107

### Previously an Issue?
No idea

### Error popup:
![image](https://user-images.githubusercontent.com/57022604/210807982-becb9a58-b9d9-41d2-a83d-422c794bb064.png)
[2023-01-05 16.49.26.log](https://github.com/Aurora-RGB/Aurora/files/10353073/2023-01-05.16.49.26.log)

**Comment by SaraJLeen** [comment]
Also happens when running Winamp or WACUP.

**Comment by Aytackydln** [comment]
Alright, I will revert media info library version. Until then if this annoys you, you can disable media info by editing %appdata%/Aurora/Config.json and changing "EnableMediaInfo" to false

**Comment by Aytackydln** [comment]
can you try with last version?
https://github.com/Aurora-RGB/Aurora/releases/tag/v111

**Comment by Shadowex3** [comment]
Working for me now with v111
