### ISSUE TITLE
Memory leak since a few Versions

### ISSUE THREAD

**Issue by cyablo** [Aurora-RGB/Aurora#119]
### Expected Behaviour
Memory consumption being sub 1 GB and Aurora Effects being fast.

### Actual Behaviour
Aurora starts to consume more and more RAM (I've seen it use the max of 4 GB of RAM) and the Effects on my Keyboard get slower until it crashes with shown Message;

![2023-01-07 09_30_24-](https://user-images.githubusercontent.com/3456720/211141666-748bd049-84fd-402b-a319-9623692368ad.png)

### Reproduction steps
Just wait for it to eat memory and crash, already ramping up after a few Minutes:

![aurora-memory](https://user-images.githubusercontent.com/3456720/211142076-3ded56af-7836-4269-b9ca-5e920c473229.JPG)

![aurora-memory2](https://user-images.githubusercontent.com/3456720/211142164-2b2768a8-7f65-46c5-bd3a-1028bf1b949d.JPG)

### Frequency
2-3 times a day, at least.

### Aurora Version:
v108

### Previously an Issue?
Yes, but can't say when it started. It could be a few days before christmas I think.

---

To help debugging, here are my Log files:

[Logs.zip](https://github.com/Aurora-RGB/Aurora/files/10365823/Logs.zip)

and my Profile I'm using:

[desktop.zip](https://github.com/Aurora-RGB/Aurora/files/10365826/desktop.zip)

**Comment by Aytackydln** [comment]
I couldn't find the main cause but I've optimized Aurora for your profile. With the layers you are using memory leak shouldn't be a problem

**Comment by cyablo** [comment]
Unfortunately doesn't help. Still running out of memory.

**Comment by Aytackydln** [comment]
https://github.com/Aurora-RGB/Aurora/releases/tag/v110
Memory profiling with this version now had no memory increase

**Comment by cyablo** [comment]
Thank you, I will test and report.

Btw: The installer does not contain CMSDK.dll and CUESDK.x64_2017.dll. Had to exctract them from source code zip file to make my CoolerMaster Keybaord work again.

**Comment by cyablo** [comment]
Sorry:

![aurora-memory3](https://user-images.githubusercontent.com/3456720/212190846-de072a30-89bc-4030-b9ac-e889ab14a6c3.JPG)

**Comment by Aytackydln** [comment]
This error doesn't always mean memory leak. This mostly happens when programs try to access incorrect memory address. Can you share me your logs?

**Comment by cyablo** [comment]
Sure:

[Logs.zip](https://github.com/Aurora-RGB/Aurora/files/10406430/Logs.zip)

**Comment by Aytackydln** [comment]
Btw, if you have low RAM you should reduce your Bitmap Accuracy. Currently that setting only affects Ambient Layer quality

![image](https://user-images.githubusercontent.com/11393706/212198298-b70dc071-8f55-467f-a81e-b2c53a1e0de8.png)

**Comment by cyablo** [comment]
I'm using Aurora for years, never had any problems like this before. Must be something that changed in the last weeks. My system has 16 GB of RAM, that shouldn't be a problem here.

**Comment by Aytackydln** [comment]
I found out that the problem is from Matrix Away effect.

Error happens from creating a line that has less than 1 unit of length. I had made check for this to not happen but seems points (20, 19.9) and (20, 20) also throws this error.

**Comment by cyablo** [comment]
That's right, I use this one. Anything I can do to help?

**Comment by Aytackydln** [comment]
No, it's easy to fix. Thanks, just reporting more bugs would help :)

**Comment by cyablo** [comment]
Sorry to be the game spoiler, but I disabled the Matrix away effect and the memory leak is still present, Aurora currently using 7 GB of RAM:

![aurora-memory4](https://user-images.githubusercontent.com/3456720/212469306-10751393-2d50-4ab7-affa-4119350a326b.JPG)

**Comment by Aytackydln** [comment]
Did the memory usage increase with the latest version or was it already happening?

Also, how long does it take to use this much memory?

**Comment by Aytackydln** [comment]
can you send me your whole %appdata%/aurora folder and tell me which games you are using?

**Comment by cyablo** [comment]
Sure:

[Aurora.zip](https://github.com/Aurora-RGB/Aurora/files/10417881/Aurora.zip)

I'm not playing any games on this Machine :)

**Comment by Aytackydln** [comment]
My guess is particle layer. I will investigate it. Btw, when I used your previous profile it had different layers

**Comment by cyablo** [comment]
Dont know. I just use one profile because no games.

![profile](https://user-images.githubusercontent.com/3456720/212477162-70c5da0d-d4ab-4afb-956d-1f7ca6d44e18.JPG)

Should look like this:

![layers](https://user-images.githubusercontent.com/3456720/212477180-06acd66b-9f29-4534-9bef-561ecdb10827.JPG)

- Percent (CPU)
- Percent (RAM)
- Lock Colour
- Lock Colour
- Interactive / Key Wave
- Particle
- Solid (for Mouse)
- Solid (for Keyboard)

**Comment by Aytackydln** [comment]
How is the memory usage on last version?

**Comment by cyablo** [comment]
Sadly that's RAM usage after about 20 hours:

![aurora-memory5](https://user-images.githubusercontent.com/3456720/212837016-f2ced689-e3ee-4863-af01-544c11cdfad1.JPG)

**Comment by cyablo** [comment]
It's not the layers, I think. Made a new profile with just a glitch Layer and it also ramps up the memory usage:

![aurora-memory6](https://user-images.githubusercontent.com/3456720/214298722-48df880d-2a43-4fc9-b446-7af98a71e30e.JPG)

Maybe it's the CoolerMaster or StelelSeries SDK?

**Comment by Aytackydln** [comment]
Steelseries sdk might be it. Coolermaster is used by many other people I know and don't have problems

**Comment by cyablo** [comment]
Steelseries integaration is using Steelseries GG SDK and not RGB.NET, right?

**Comment by cyablo** [comment]
Didn't know it has a fancy name :) I could try dowgrading SteelSeries GG Software to see if that changes something.

**Comment by Aytackydln** [comment]
Also, I will add rgb.net implementation next build. Maybe that is better

**Comment by Aytackydln** [comment]
added rgb.net implementation:
https://github.com/Aurora-RGB/Aurora/releases/tag/v116

**Comment by cyablo** [comment]
Doesn't look like that solved the Issue. RAM usage is still gooing up up up ... :(

![aurora-memory7](https://user-images.githubusercontent.com/3456720/215350517-55ec43d0-596a-4c25-bf81-ec181beba259.JPG)

**Comment by Aytackydln** [comment]
How long was aurora open with this screenshot? If you're using Ambilight Layer up to 1.5GB usage is okay

**Comment by cyablo** [comment]
Under 5 MInutes. Not using Ambilight Layer. Memory usage starts at about 250 MB and increases until Aurora freezes/crashes.

**Comment by cyablo** [comment]
10 Gigs of RAM, yay!

![aurora-memory8](https://user-images.githubusercontent.com/3456720/215403454-cb667f88-e3f4-46f7-a216-8a7b538c4c3e.JPG)

It's not the layer, new Profile with onyl one Glitch Layer also has the same beavior.
It's not the SteelSeries Integration.

What is causing this and why I'm the only one experiencing it?

**Comment by Aytackydln** [comment]
there are still some things you can close. %appdata%/Aurora/Config.json EnableAudioCapture, EnableMediaInfo, EnableInputCapture
Not too likely they are problems but you can try.

Otherwise I don't think I can find what's the cause without profiling your memory. I can also suggest Artemis-RGB if you don't want to use Aurora anymore

**Comment by cyablo** [comment]
Disabling the said Optiosn didn't help, as expected.

To be honest, I was very pleased with Aurora since I got my MasterKeys in 2019. It get's the job done and the effects look nice and it has a lot of them to layer up.

I tried Artemis, but the Wiki on Effects is missing and it seems to be way more complex if not impossible to achieve the same effect layers I'm used to from Aurora.

**Comment by Aytackydln** [comment]
I've fixed a memory leak last patch. Can you check again?
https://github.com/Aurora-RGB/Aurora/releases/tag/v129

**Comment by cyablo** [comment]
Will test and report!

**Comment by cyablo** [comment]
Seems to be fixed indeed.
