### ISSUE TITLE
Version 116 causes Overwatch to crash

### ISSUE THREAD

**Issue by ShizCalev** [Aurora-RGB/Aurora#127]
[2023-01-28 16.57.06.log](https://github.com/Aurora-RGB/Aurora/files/10528377/2023-01-28.16.57.06.log)
[2023-01-28 15.48.04.log](https://github.com/Aurora-RGB/Aurora/files/10528378/2023-01-28.15.48.04.log)
[2023-01-28 16.55.28.log](https://github.com/Aurora-RGB/Aurora/files/10528379/2023-01-28.16.55.28.log)

### Expected Behaviour

The game to work

### Actual Behaviour

The game crashes 15~30 seconds into a match
![image](https://user-images.githubusercontent.com/6209658/215292996-053781a1-09b5-42ed-8103-5edb4954b06b.png)

### Reproduction steps

Upgrade to v116
Launch overwatch
Join a match
Game crashes 15~30 seconds in

### Frequency

100%. You cannot play the game while running aurora v116. 

### Aurora Version:

v116

### Previously an Issue?

No, version 115 does not crash. 

Downgrading from v116 to v115 instantly resolves the crashing.

**Comment by Aytackydln** [comment]
I assumed crash was because of broken audio detection from previous version. Can you try last version?
https://github.com/Aurora-RGB/Aurora/releases/tag/v117

**Comment by ShizCalev** [comment]
Sorry for the delay. The crash is still occurring on v118

**Comment by ShizCalev** [comment]
Narrowed it down to being caused by having G.SKILL Trident Z Lighting Control (lighting control software for my RAM) open at the same time as Aurora. I can have either Aurora or the gskill lighting open and no ctd, but both of them open results in a ctd.
`https://www.gskill.com/download/1502180912/1551690847/Trident-Z-Family-RGB,-Neo,-Royal,-Royal-Elite,-Z5-RGB`


It occurs in all gamemodes for me, even practice / firing range.

**Comment by Aytackydln** [comment]
only possible relevant change with v116 looks like steelseries (rgb.net) controller. Can you try with that disabled?

**Comment by ShizCalev** [comment]
Got everything but Logitech and both Corsair controllers disabled, no joy. 
![image](https://user-images.githubusercontent.com/6209658/218344179-24d946a6-0d5e-48e7-8532-90c1c8a8180c.png)

**Comment by Aytackydln** [comment]
I installed G.SKILL Trident Z Lighting Control and it didn't crash for me. It is probably Chroma SDK related. I suggest installing latest version
