### ISSUE TITLE
Audio Visualizer No Longer Follows Default Audio Device in v116

### ISSUE THREAD

**Issue by HorseOfTheSea** [Aurora-RGB/Aurora#128]
### Expected Behaviour

Audio visualizer layers continue to display on keyboard when "default" is set as audio device

### Actual Behaviour

[2023-01-28 22.55.55.log](https://github.com/Aurora-RGB/Aurora/files/10528965/2023-01-28.22.55.55.log)
Audio visualizer layer no longer displays to keyboard, while other layers continue

### Reproduction steps

Have audio visualizer layer with "Default" set as audio device
Switch audio device within Windows
Audio visualizer layer no longer displays to keyboard, appearing to never switch monitoring the new default output device
Functionality is restored upon reverting default device in Windows, or manually specifying the specific device in Aurora

### Frequency
Every Time

### Aurora Version:

v116
### Previously an Issue?

No, not in issue in v115 or the last few prior

**Comment by Aytackydln** [comment]
Hopefully fixed:
https://github.com/Aurora-RGB/Aurora/releases/tag/v117

**Comment by HorseOfTheSea** [comment]
Upgraded and confirmed this is resolved in v117. Thank you :)
