### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Werve** [Aurora-RGB/Aurora#134]
### Expected Behaviour

Just start without warnings or errors.

### Actual Behaviour
Crash at startup, show errors windows. 

### Reproduction steps

Just at the startup (Windows login or manually open) it crash and show the following windows:
![image](https://user-images.githubusercontent.com/13850028/217802257-e8639492-b003-4432-acb6-3359501e649c.png)
![image](https://user-images.githubusercontent.com/13850028/217802326-a6893765-441e-412a-8286-dd1cfb9a4032.png)

Log attached.
[2023-02-09 12.24.10.zip](https://github.com/Aurora-RGB/Aurora/files/10696698/2023-02-09.12.24.10.zip)

### Frequency

Every times, since I got the issue of ProgramData folder corrupted.
Already tried to reinstall Aurora.

### Aurora Version:

120

### Previously an Issue?

No, but sometimes it showed anyway the httplisten error windows, without crash.

**Comment by Werve** [comment]
> You might have another program running on port 9088 that causes this error for you.

It is likely, over the last few weeks several programs (even BOINC) sometimes refuse to connect because they can't find a free port 😅

**Comment by Aytackydln** [comment]
solved:
https://github.com/Aurora-RGB/Aurora/releases/tag/v122

**Comment by Werve** [comment]
I installed the new version and confirmed that it opened. But actually the previous one had also managed to start today, maybe it had found a free port. 
Anyway, thank you.

**Comment by Werve** [comment]
Actually after a PC reboot it happened again.

![image](https://user-images.githubusercontent.com/13850028/218437751-9a1e93fe-b292-41ad-a41e-1f3130e9541c.png)

Log:
[2023-02-13 11.41.04.zip](https://github.com/Aurora-RGB/Aurora/files/10721423/2023-02-13.11.41.04.zip)

**Comment by Werve** [comment]
I confirm it worked, had the same httplistener error but without aurora crashing then it opened correctly.

**Comment by Aytackydln** [comment]
If you don't want to see the error every launch you can disable the module
