### ISSUE TITLE
Aurora Connection Failure

### ISSUE THREAD

**Issue by SlytherinGurl77** [Aurora-RGB/Aurora#135]
So, Aurora says connection failure. When I try to install the supported version of chroma's I get an error (in attached photo) and then the chroma doesn't install. Also aurora won't work with Overwatch 2. I am also attaching my latest log file. 

### Expected Behavior
Aurora should be connected and installed version of Chroma should be enabled. . 

### Actual Behavior
Aurora says connection failure and won't install chroma's. Aurora won't work with Overwatch 2. 

### Frequency
Happens every time I open Aurora, even if I open it with a different version.

### Aurora Version:
I am using version v127, but it happens on every version I've tried. 

### Previously an Issue?
It wasn't an issue for me until a few days ago when I updated from v120 to v127. It worked just fine, even with Overwatch 2. 

![Aurora Error 2-18-2023](https://user-images.githubusercontent.com/108553503/219848493-76fac3ef-f79a-42b9-bc18-54706a56b5c6.png)
![Aurora Error #2 2-18-2023](https://user-images.githubusercontent.com/108553503/219848496-47b8ab18-326b-469a-8d2f-eb959610465b.png)
[2023-02-18 02.30.19.log](https://github.com/Aurora-RGB/Aurora/files/10773627/2023-02-18.02.30.19.log)

**Comment by Aytackydln** [comment]
Sorry for late response but did you try it after pc restart?

**Comment by SlytherinGurl77** [comment]
Yes I have. I've even tried uninstalling and reinstalling a previous version that I did work on before, and it still says Connection Failure and does not work with Overwatch 2.

**Comment by Aytackydln** [comment]
I've done uninstall & install today myself. Something you have to do is restart pc right after uninstallation.

Do you have synapse installed? Maybe that messes with chroma

**Comment by SlytherinGurl77** [comment]
I'm not sure. How do check to see if it's installed and how do I install synapse if it's not?

**Comment by Aytackydln** [comment]
You can check Apps & Features in Windows. If not installed you can download it from Razer's website

**Comment by SlytherinGurl77** [comment]
It still says connection failure. I tried installing it. It still won't work with Overwatch either.

**Comment by Aytackydln** [comment]
Hopefully this is fixed already :)

**Comment by SlytherinGurl77** [comment]
Yes it is. The new updates fixed it somehow. Thank you!
