### ISSUE TITLE
Guild Wars 2: LightFX Wrapper not working after v65

### ISSUE THREAD

**Issue by keiichi000** [Aurora-RGB/Aurora#136]
Starting after v65 of Aurora-RGB, the LightFX wrapper has not worked properly with Guild Wars 2's LightFX integration.  With the current wrapper provided by v128, Guild Wars 2 can not detect that LightFX is available and will not allow you to enable it.  With the wrapper v65 and with AuroraRGB v65, Guild Wars 2 could detect that LightFX was enabled, would allow you to turn on the integration, and the games integrated lights would show up in AuroraRGB.  

If you take the wrapper from v65 and use it with any version of Aurora after that, the LightFX Layer does not respond to the game client, even though the client will still show the integration is enabled.

**Comment by keiichi000** [comment]
Okay, figured this out.  Apparently the LightFX DLL file location may have moved.  It used to be in the just Guild Wars 2 root folder.  That didn't work at all for me.  But, if I copied the DLL into the Guild Wars 2/bin64 directory, suddenly its working again.  

So, this may be less about the DLL having issues, and more that the DLL instructions might need to be changed?  I'll let you all decide if this needs to still be a bug, or if you want to close it, since the issue is resolved for me.  I don't know if anyone else can replicate this as being an issue.  Thanks!

**Comment by Aytackydln** [comment]
Changed the description, thanks
