### ISSUE TITLE
I want Aurora to only work when a specific process is running.

### ISSUE THREAD

**Issue by ocformula** [Aurora-RGB/Aurora#139]
I want Aurora to only work when Overwatch is running.

I use Aurora to take advantage of Overwatch's chroma lighting.
I check the profile of Corsair keyboard through lighting.
so it's hard to use Aurora all the time.
So I only run Aurora when I'm playing Overwatch, which is very inconvenient.
It would be nice to have the ability to set Aurora to only work when certain processes are running.

**Comment by Aytackydln** [comment]
Sorry for really late response but I've implemented this on latest release

https://github.com/Aurora-RGB/Aurora/releases/tag/v145
