### ISSUE TITLE
Memory leak still present

### ISSUE THREAD

**Issue by codemastermick** [Aurora-RGB/Aurora#146]
I hate to bring this up again, but it clearly isn't fixed yet.... I've been dealing with this since before the fork, and it hasn't gotten any better throughout the versions. I assume there must be something with my setup, but this happens with a totally unmodified installation. No changes to any profiles at all, nothing customized, and it will still do this. If I do add customization to any of the profiles it does not make any difference to the issue, positive or negative.

### Expected Behaviour
The application *should* be running within normal memory limits.

### Actual Behaviour
Something is still leaking, causing it to take an **incredible** amount of memory.
<img width="640" alt="image" src="https://user-images.githubusercontent.com/51538065/226183403-79845c23-7e83-40d1-9d68-a811fc8ccd55.png">

### Reproduction steps
Simply launch Aurora and wait a while. I usually wake up each morning to an OOM error if I forget to close Aurora entirely before going to bed.

### Frequency
Every single time. I reboot my machine because of OOM errors due to Aurora more than anything else.

### Aurora Version:
v131

### Previously an Issue?
Yes, has been an ongoing issue for many versions now, even after applying every known fix that has been reported to work thus far.

**Comment by codemastermick** [comment]
Running on v151, issue still present:
<img width="664" alt="image" src="https://github.com/Aurora-RGB/Aurora/assets/51538065/71a35289-6736-4e64-a1b3-9b0f7e3a5721">

It would be nice to have any kind of feedback on this. If you can point me in a direction to look I am more than willing to try to debug the issue with you. I love the software and really don't want to give it up, but if this issue cannot be resolved I might have to.

**Comment by Aytackydln** [comment]
Okay, since your memory leak issue is really noticable you can try going back in versions and tell me which version it started.

Sorry, I've already spent lots of time and have no idea

**Comment by crycx** [comment]
I have the same issue, for me the version 143 works normal. I'm using it with Logitech  G915 and G502 Lightspeed

**Comment by crycx** [comment]
The newest version did not fix the memory leak :(

**Comment by crycx** [comment]
@Aytackydln do you want me to start moving up from version 143 ? Sometimes even 143 will have this issue. But it may be that many days it will not do it.

**Comment by Aytackydln** [comment]
If you had it on v143 then there's no point in trying with later versions

**Comment by Aytackydln** [comment]
Hey everyone, please try the latest version and give feedback:

https://github.com/Aurora-RGB/Aurora/releases

**Comment by mrgirboto** [comment]
Seems like just having it open for an extended period of time triggers alerts such as the ones below. 

![image](https://github.com/Aurora-RGB/Aurora/assets/61300289/8a99ec6e-ea86-4cfd-bef7-f21116ea6267)
![image](https://github.com/Aurora-RGB/Aurora/assets/61300289/cfcf693f-3962-4bd7-940c-1a7b16131374)
![image](https://github.com/Aurora-RGB/Aurora/assets/61300289/bb211ccc-cc24-4a7d-bd20-8fc023206ecb)

**Comment by Aytackydln** [comment]
@mrgirboto can you upload your logs?

**Comment by mrgirboto** [comment]
[2023-08-26 12.29.38.log](https://github.com/Aurora-RGB/Aurora/files/12446630/2023-08-26.12.29.38.log)
[2023-08-26 12.34.15.log](https://github.com/Aurora-RGB/Aurora/files/12446631/2023-08-26.12.34.15.log)

It generated a couple around the same time.

**Comment by Aytackydln** [comment]
What about last version? (not hopeful this time)

**Comment by crycx** [comment]
@Aytackydln i'll monitor the new version for couple of days and will let you know :)

**Comment by mrgirboto** [comment]
Yo @Aytackydln 
![image](https://github.com/Aurora-RGB/Aurora/assets/61300289/05bfaf80-41c8-4911-9995-22ec6fd7998d)
[2023-08-29 17.24.09.log](https://github.com/Aurora-RGB/Aurora/files/12491031/2023-08-29.17.24.09.log)

This was the error message and logs from the crash today 2023-08-31 (log file was created two days ago, but it has information about today's crash). This was version 180

**Comment by Aytackydln** [comment]
@mrgirboto Thanks! I think you logs finally made me realize the problem.

Please update to the latest version manually (Sadly updater is broken sice v180 😞)
https://github.com/Aurora-RGB/Aurora/releases

**Comment by mrgirboto** [comment]
![image](https://github.com/Aurora-RGB/Aurora/assets/61300289/c5ddd590-7df7-42f3-a74d-3bb5129ad725)
![image](https://github.com/Aurora-RGB/Aurora/assets/61300289/d5743b58-6b71-4ea5-9a9a-88d19ee77475)
[2023-09-01 21.22.52.log](https://github.com/Aurora-RGB/Aurora/files/12564594/2023-09-01.21.22.52.log)

I am on v185. Seems like it might be related to audio visualizer? when the errors happen, the ripple effects still occur but the audio visualizer stops working.

**Comment by mrgirboto** [comment]
@Aytackydln forgot to @ you for the post with the logs, but overall it seems better though/lasted longer before the error.
