### ISSUE TITLE
Aurora process does not end when selecting "Quit."

### ISSUE THREAD

**Issue by tianders295** [Aurora-RGB/Aurora#147]
### Expected Behaviour
The Aurora process should end when "Quit" is selected.

### Actual Behaviour
When selecting "Quit," the lighting does stop working, the window closes, and the icon disappears from the system tray, but the process still runs in the background with decreased memory usage.

Before selecting "Quit:"
![background_processes_aurora_before](https://user-images.githubusercontent.com/27469346/226406962-e4a2b2db-b524-47de-a923-e4069733f027.jpg)

After selecting "Quit:"
![background_processes_aurora_after](https://user-images.githubusercontent.com/27469346/226406965-0120193a-f12e-4461-94a1-bef63947edae.jpg)

### Reproduction steps
1. Start Aurora as normal
2. Open Task Manager
3. Right-click on the system tray icon, and select "Quit."

### Frequency
This issue occurs every single time "Quit" is selected.

### Aurora Version:
v131

### Previously an Issue?
Versions before the fork did not have this issue, but I first noticed the issue with v128.

### Environment
- Windows 10 (Build 19045)
- Corsair K95 Platinum keyboard (with iCUE 4.33)
- Logitech G502 HERO mouse (with G HUB 2023.2)

### Log files
[2023-03-20 12.32.03.log](https://github.com/Aurora-RGB/Aurora/files/11020918/2023-03-20.12.32.03.log)
[2023-03-19 13.54.11.log](https://github.com/Aurora-RGB/Aurora/files/11020933/2023-03-19.13.54.11.log)

**Comment by Aytackydln** [comment]
Is this still a problem?
