### ISSUE TITLE
Forza Horizon 5 crashes upon startup 

### ISSUE THREAD

**Issue by voed** [Aurora-RGB/Aurora#148]
### Expected Behaviour
Run Forza Horizon 5

### Actual Behaviour
Game crashes

### Reproduction steps
Run Aurora
Run FH5

### Frequency
Every time

### Aurora Version:
131

### Previously an Issue?
Not sure if it caused by game updates or Aurora updates, started few month ago

Actually, i am not using game profiles in Aurora, only desktop shortcuts highlight, so maybe we can have some option to disable games scanning/injecting at all?

**Comment by joaocaparroz** [comment]
I'm having the same problem.
Probably it's something related to Forza's anti-cheat system.

**Comment by Aytackydln** [comment]
Found out game blacklisted Aurora.exe and implemented a shutdown mechanism for Aurora.

Nothing I can do for now. Maybe we could pressure developers for whitelisting Aurora
