### ISSUE TITLE
Aurora 1.31 Crashes playing Elite Dangerous

### ISSUE THREAD

**Issue by darkmikau** [Aurora-RGB/Aurora#150]
Hello guys, I believe I found a bug. After playing Elite Dangerous for a couple minutes, Aurora 1.31 Crashes with the error attached.

### Expected Behaviour
Aurora should be working

### Actual Behaviour
Aurora crash after playing the game for a while.

### Reproduction steps
I flew from a system to another, them went to any space station and docked.

### Frequency
Cant figure, it seems like it crashes trying to read some game files.

### Aurora Version:
1,31

### Previously an Issue?
I don't know

![AuroraEliteDangerousCrash](https://user-images.githubusercontent.com/16527105/231050997-dfea3b0f-d97d-4ffd-8eff-f84774fea8ac.png)

**Comment by Aytackydln** [comment]
Seems like that file has unnecessary lines or wrong characters there. Can you also share the log file?

Please just send the file, posting file content ruins thread readability

**Comment by darkmikau** [comment]
Thanks man, gonna try it later!
