### ISSUE TITLE
Asus (RGB.NET) not working

### ISSUE THREAD

**Issue by joaocaparroz** [Aurora-RGB/Aurora#154]
### Expected Behaviour
Aurora controls MB and VGA LEDs

### Actual Behaviour
Asus (RGB.NET) can't initialize. The following message is presented: "Device provider "Asus (RGB.NET)" threw exception System.IO.FileNotFoundException: Could not load file or assembly 'Interop.AuraServiceLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified."

### Reproduction steps
Just open the program

### Frequency
Every time

### Aurora Version:
v143

### Previously an Issue?
No. It worked in v131.

[2023-05-27 09.49.20.log](https://github.com/Aurora-RGB/Aurora/files/11581958/2023-05-27.09.49.20.log)
![image](https://github.com/Aurora-RGB/Aurora/assets/19500222/c834f808-ec90-4d11-914a-61967431e7e1)

**Comment by Aytackydln** [comment]
Thanks for the report. I'm trying to fix it

**Comment by atfield90** [comment]
Same here. Do you need any logs for this one?

**Comment by Aytackydln** [comment]
Didn't need. After lots of work I finally managed to fix it. I will make the release once I fix other bug I have locally 👍🏻

**Comment by Aytackydln** [comment]
Can you try the latest release?

https://github.com/Aurora-RGB/Aurora/releases/tag/v144

**Comment by atfield90** [comment]
yes it's working now!

thanks a lot :)
