### ISSUE TITLE
Crash when Starting Aurora after Update to v145 - Error Loading Xceed.Wpf.Toolkit.NET5

### ISSUE THREAD

**Issue by MattJF90** [Aurora-RGB/Aurora#156]
### Precondition
Install v144, then upgrade to v145

### Reproduction steps
1. Launch Aurora

### Expected Behaviour
Aurora starts successfully

### Actual Behaviour
Aurora crashes on startup

### Frequency
Every time

### Aurora Version:
v145

### Previously an Issue?
No

### Crash Exception Message
Fatal Exception caught : System.Windows.Markup.XamlParseException: Set connectionId threw an exception.
 ---> System.BadImageFormatException: Could not load file or assembly 'Xceed.Wpf.Toolkit.NET5, Version=4.5.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4'. Format of the executable (.exe) or library (.dll) is invalid.
File name: 'Xceed.Wpf.Toolkit.NET5, Version=4.5.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4'

### Log
[2023-06-10 23.23.45.log](https://github.com/Aurora-RGB/Aurora/files/11713776/2023-06-10.23.23.45.log)

### Screenshot
![image](https://github.com/Aurora-RGB/Aurora/assets/897065/a6396b4f-c6a9-4884-afc2-72f6444c8880)

**Comment by MattJF90** [comment]
Note that the previous released version (v144) worked correctly. This crash seems to have been introduced by upgrading from v144 to v145.

**Comment by Aytackydln** [comment]
Can you try a clean installation?

**Comment by MattJF90** [comment]
Just did a clean installation and it seemed to work correctly. So this bug only seems to affect upgrading from an older version.

**Comment by Aytackydln** [comment]
I'm assuming this was because of a corrupted download
