### ISSUE TITLE
[Request] Add headset support

### ISSUE THREAD

**Issue by greggameplayer** [Aurora-RGB/Aurora#158]
Please add support for headset such as :

**Device Name:** Steelseries Arctis 5

**Device Website:** https://fr.steelseries.com/gaming-headsets/arctis-5

You currently might be able to control the light of it through openrgb

**Comment by Aytackydln** [comment]
You should be able to use headset in pre-release version:
https://github.com/Aurora-RGB/Aurora/releases

Please try it and give feedback if you have problems
