### ISSUE TITLE
Left click state stays true indefinitely after initial click

### ISSUE THREAD

**Issue by dondonini** [Aurora-RGB/Aurora#161]
### Expected Behaviour
Left-click to say `false` when it is unpressed

### Actual Behaviour
Left-click status sticks to `true` state

### Reproduction steps

1. Select any layer
2. Go to the conditional layer menu ![image](https://github.com/Aurora-RGB/Aurora/assets/18273458/1c15edd6-654d-437a-b48c-f6a11a6a214e)
3. Go to the "Enabled" property in the list and set "Override mode" to "Dynamic Value"
4. Go to the "Input" tab at the bottom and drag the ![image](https://github.com/Aurora-RGB/Aurora/assets/18273458/1022f5be-2691-40fe-acca-4321be844d30) value to replace the default ![image](https://github.com/Aurora-RGB/Aurora/assets/18273458/90f363f1-206c-40ab-a828-1c79deb587f8) value
5. Enable the "Debug values" checkbox near the top right to see raw values

The steps above are to see the raw values; however, this affects anything in Aurora that uses the left-click-down value.
E.g.: Layer type "Interactive" - the "Mouse Effect Key" stays on even after I release my left-click. Right-clicking does cancel it out.

### Frequency
Permanently after the first left click

### Aurora Version:
1.60

### Previously an Issue?
Nope

**Comment by Aytackydln** [comment]
Thanks! There was a stupid mistake in my code. Will be fixed in next build

**Comment by Aytackydln** [comment]
https://github.com/Aurora-RGB/Aurora/releases/tag/v163

**Comment by dondonini** [comment]
It seems like the left click is fixed; however, now all of the other buttons don't work (Right click, middle click, etc.).

**Comment by Aytackydln** [comment]
Yes, that's what I intended. I will add other button presses later

**Comment by dondonini** [comment]
Sounds good! Thanks :D
