### ISSUE TITLE
Aurora 163 only shows a grey screen after opening

### ISSUE THREAD

**Issue by ShizCalev** [Aurora-RGB/Aurora#162]
### Expected Behaviour

It to open

### Actual Behaviour

This screen loads, then nothing else happens
![image](https://github.com/Aurora-RGB/Aurora/assets/6209658/176f9569-e125-4842-90a2-95d662ecd4f6)

With old settings present:
[2023-07-28 14.44.3420230728.log](https://github.com/Aurora-RGB/Aurora/files/12197460/2023-07-28.14.44.3420230728.log)
After deleting my settings from appdata:
[2023-07-28 14.47.4320230728.log](https://github.com/Aurora-RGB/Aurora/files/12197528/2023-07-28.14.47.4320230728.log)

### Reproduction steps

Install 163. Open it.

### Frequency

Every time.

### Aurora Version:

163

### Previously an Issue?

Issue was not present with 160.

**Comment by Aytackydln** [comment]
Last patch had a fix for this case. This can happen if UI is opened before one of the module is initialized.

I couldn't reproduce this even when I change code to make this module not load. I can see 2 other possibility for now.
1. When you open Aurora two processes are created. Second one immediately sending "Display" command when it is available.
2. Opening Aurora from tray

I need to do some clever refactoring to actually fix this issue, but can you check if these 2 cases don't happen?

**Comment by MrWolfRanger** [comment]
i recreated it by just installing it, updating or anything with aurora now....

**Comment by Aytackydln** [comment]
Alright, please test last build:
https://github.com/Aurora-RGB/Aurora/releases

**Comment by Khurune** [comment]
Could it be related to the UI transparency? Might be worth having that set to false as default instead of true.
Using v164 on win11 with no issues currently.

**Comment by Aytackydln** [comment]
No, it is caused by a dead-lock. It depends on background processes created by Aurora and the machine's thread count. I've solved related (hopefully) dead-locks but need confirmation

**Comment by broli95** [comment]
I still have this problem with the latest version

**Comment by Aytackydln** [comment]
Thank you for feedback. Please check with last pre-release

https://github.com/Aurora-RGB/Aurora/releases

**Comment by broli95** [comment]
> Thank you for feedback. Please check with last pre-release
> 
> https://github.com/Aurora-RGB/Aurora/releases
![image](https://github.com/Aurora-RGB/Aurora/assets/22918304/034ba5a3-c7e1-48ac-80f3-83b213569d16)
 Getting this error when trying to install the latest pre-release

**Comment by Aytackydln** [comment]
Did you use Aurora's updater? If not, did you fully close Aurora?

This is the first time I see this. Maybe you just need a restart after disabling auto launch

**Comment by broli95** [comment]
> Did you use Aurora's updater? If not, did you fully close Aurora?
> 
> This is the first time I see this. Maybe you just need a restart after disabling auto launch

NVM it seems it worked now, thank you
