### ISSUE TITLE
Missing v167 with Chocolatey

### ISSUE THREAD

**Issue by ryanhatfield** [Aurora-RGB/Aurora#164]
I haven't looked yet if you have anything to do with the Chocolatey package management system, but why did you delete release v167?

`choco install project-aurora` currently fails looking for v167.
![image](https://github.com/Aurora-RGB/Aurora/assets/12716395/b63f2fa0-ea18-4bb4-8040-e4e4a84c31d2)

**Comment by ryanhatfield** [comment]
In case anyone happens upon this, specifying the version works through chocolatey still, even though their version cache hasn't updated yet.

`choco install project-aurora --version 168`

**Comment by Aytackydln** [comment]
It had some major issues that wasn't okay for a release. Made it pre-release until I fixed them
