### ISSUE TITLE
Aurora V169 completely breaks Logitech Gaming Software incl basic mouse functionality

### ISSUE THREAD

**Issue by D3SL** [Aurora-RGB/Aurora#166]
### Expected Behaviour
Aurora should have absolutely no interaction with my mouse's ability to rebind buttons or change sensitivity.

### Actual Behaviour
Aurora v169, possibly v168 as well, completely breaks Logitech Gaming Software.  The process starts but does not function, leaving my mouse's basic functionality crippled.

### Reproduction steps
Have a pre-GHub mouse like a G500 and try to use it at the same time as Aurora V169

### Frequency
Every time

### Aurora Version:
V169, maybe V168

### Previously an Issue?
Possibly V168
V166 is confirmed not to cause this issue.

**Comment by Aytackydln** [comment]
Thanks for reporting this. Can you tell me the process name of LGS in task manager so that I can disable Lightsync if it is open?

**Comment by D3SL** [comment]
Mine is LCore.exe. The process will start with V169 but the software won't be functional. I don't know if you could get around this by switching the mouse to onboard mode beforehand, however doing that loses game detection.

**Comment by brianbruno** [comment]
Same problem here, but with keyboard G512.
I tryed to update the GHUB and all logitech drivers related, but anything solved the problem.

**Comment by Aytackydln** [comment]
You can use the last version now

**Comment by Aytackydln** [comment]
@brianbruno do you have the same issue with GHUB?
