### ISSUE TITLE
Aurora crashes every time I try to disable any Razer devices

### ISSUE THREAD

**Issue by dondonini** [Aurora-RGB/Aurora#167]
### Expected Behaviour

Disable Razer or Razer (RGB.NET)

### Actual Behaviour

Crashes with following prompt: 
![image](https://github.com/Aurora-RGB/Aurora/assets/18273458/02280726-af57-4f81-b5ae-62a324981de7)

Additionally, any Razer API is now permanently on

### Reproduction steps

1. Open Aurora
2. Go to General Settings
3. Go to the Device Manager tab
4. If Razer or Razer (RGB.NET) is disabled, enable it here
5. Proceed to try to disable either Razer devices

Log: [2023-08-09 15.45.59.log](https://github.com/Aurora-RGB/Aurora/files/12306387/2023-08-09.15.45.59.log)

### Frequency

Every time I try to disable anything Razer device related

### Aurora Version:

v170

### Previously an Issue?

Nope

**Comment by Aytackydln** [comment]
I didn't have this issue on my local build (maybe fixed already?)
Can you check with latest version?

**Comment by dondonini** [comment]
This seems to be fixed on the latest build (v171). Thanks!
