### ISSUE TITLE
Macro keys on a Razer Blackwidow Chroma start unassigned using OpenRGB initially and on every update

### ISSUE THREAD

**Issue by dondonini** [Aurora-RGB/Aurora#168]
### Expected Behaviour

All macro keys on my Blackwidow start assigned correctly from the start

### Actual Behaviour

All macro keys start unassigned

### Reproduction steps

1. Install Aurora and OpenRGB
2. Go to General Settings
3. Go to the Device Manager tab and enable OpenRGB
4. Go to Remap Devices and click `[Keyboard] Razer Blackwidow Chroma #________`

In addition, after assigning the keys to their correct mappings (M1 = G1, M2 = G2, etc.) they would unassign after an update or randomly without notice.

### Frequency

Every update or a few days

### Aurora Version:

I think I found it on ~v165
Currently on v171

### Previously an Issue?

Technically yes ever since I switched from Razer (RGB.NET) to OpenRGB

**Comment by Aytackydln** [comment]
Yes, this is a recently known issue related to OpenRGB. You can still make it work though.

Synapse can't save macro settings while OpenRGB is open. If you are ever going to open Synapse, close OpenRGB first. Then you can save macros and open OpenRGB after closing Synapse.

If it still doesn't work you may need to reset your device in Synapse

**Comment by Aytackydln** [comment]
Sorry I misunderstood your situation. Can you upload your logs?

**Comment by dondonini** [comment]
I'm sorry for not getting back to you sooner, but after a few updates, it seems like it's staying mapped correctly even after a few updates. I'll point this out again if it happens.
