### ISSUE TITLE
Corsair K70 RGB PRO not being detected in device manager

### ISSUE THREAD

**Issue by PurplePanda2001** [Aurora-RGB/Aurora#173]
### Expected Behaviour

K70 keyboard shows up in device manager and I can use Aurora with it

### Actual Behaviour

K70 never shows up in Aurora and I can't use it
![image](https://github.com/Aurora-RGB/Aurora/assets/13228092/e5434f8e-fbf9-4c90-b895-75830fc0ea34)

### Reproduction steps

1.  Start iCUE
2.  Start Aurora
3.  Check device manager in settings to see if keyboard is detected
4.  Keyboard is not detected and I can't use Aurora

### Frequency

Everytime

### Aurora Version:

v185

### Previously an Issue?

Don't know, first time using Aurora

### Log
[2023-09-06 15.33.59.log](https://github.com/Aurora-RGB/Aurora/files/12542377/2023-09-06.15.33.59.log)

**Comment by PurplePanda2001** [comment]
Uh, it's just working now after a few hours for no reason so I'm just gonna close this

**Comment by Aytackydln** [comment]
Glad it's somehow solved
