### ISSUE TITLE
"idle_type" is ignored after restarting the app since v176

### ISSUE THREAD

**Issue by azumukupoe** [Aurora-RGB/Aurora#178]
### Expected Behaviour

Away Effect Type to follow "idle_type" value
### Actual Behaviour

"idle_type" is ignored and dim is used for away effect
### Reproduction steps

Install Aurora v176 or later
set Away Effect Type to something other than None or Dim
restart Aurora
"idle_type" is ignored and dim is used for away effect until you change the "idle_type" value to something else then to your desired value
### Frequency

every time
### Aurora Version:

v176, v177, v178, v179, v180, v182, v183, v184, v185, v186
### Previously an Issue?

No

**Comment by Aytackydln** [comment]
Thanks for reporting this. Please confirm with the latest version

https://github.com/Aurora-RGB/Aurora/releases
