### ISSUE TITLE
With Aurora enabled, CK550's caps and num lock leds don't turn on  

### ISSUE THREAD

**Issue by red9350** [Aurora-RGB/Aurora#18]
Expected:
The keyboard's Caps, Num and Scroll lock leds should turn on and off, when caps/num/scroll lock are either on or off

Actual:
They don't while Aurora is doing it's magic.

I tried mapping white to the Additional Lights around the keyboard in the GUI, but no luck.

Keyboard model: Cooler Master CK550, tried with all Preferred Keyboard Cooler Master models

**Comment by Aytackydln** [comment]
Are you connecting with OpenRGB? If so led mapping may be missing.

Can you tell me the led names for the lock leds in OpenRGB? You can see them easily by switching to LED View, then clicking them
![image](https://user-images.githubusercontent.com/11393706/151696995-461d0110-3846-42ad-971a-5652b142493c.png)

**Comment by Aytackydln** [comment]
Also, are those leds in your layout? I mean if they are visible inside aurora?

**Comment by red9350** [comment]
I'm connecting with CoolerMaster. Also the LEDs are not visible in the layout (they're separate from the keys, they're in the top right corner, [see here ](https://www.memoryc.com/images/products/bb/image_6244837.jpg))

**Comment by Aytackydln** [comment]
Ok, so to fix it with CoolerMaster's connector we need to find value of those leds, which I can't do it without sdk manual.

If you're not using macros I suggest connecting with OpenRGB, fix would be fast. If you still want fix for CM connector I need to find the manual first, then I can fix it (IF sdk exposes those leds)

**Comment by tgcgh** [comment]
Hi, Got the same problem, just checked and sdk 28 is out, no idea if this can help fix the issue, thanks!

**Comment by Aytackydln** [comment]
SDK 28 doesn't support either. There's nothing we can do with the SDK right now.
