### ISSUE TITLE
Logitech (RGB.NET) doesn't works with G915 and G502 X Plus

### ISSUE THREAD

**Issue by joaocaparroz** [Aurora-RGB/Aurora#181]
### Expected Behaviour
G915 and G502 X Plus can be illuminated with the software

### Actual Behaviour
Logitech (RGB.NET) doesn't works with G915 and G502 X Plus.
The Device Manager tab shows: "An item with the same key has been already been added. Key: 1"

### Reproduction steps
Just run the program

### Frequency
Everytime

### Aurora Version:
v194

### Previously an Issue?
Yes

**Comment by joaocaparroz** [comment]
[2023-11-16 12.00.55.log](https://github.com/Aurora-RGB/Aurora/files/13379327/2023-11-16.12.00.55.log)

**Comment by Aytackydln** [comment]
If using pre-release if fine for you, can you try with latest pre-release?
