### ISSUE TITLE
Devices not starting automatically

### ISSUE THREAD

**Issue by tcutchi** [Aurora-RGB/Aurora#184]
[2023-12-06 18.02.33.log](https://github.com/Aurora-RGB/Aurora/files/13592941/2023-12-06.18.02.33.log)
[2023-12-06 18.03.47.log](https://github.com/Aurora-RGB/Aurora/files/13592942/2023-12-06.18.03.47.log)
[2023-12-06 18.05.15.log](https://github.com/Aurora-RGB/Aurora/files/13592945/2023-12-06.18.05.15.log)

### Expected Behaviour
Devices start up and follow Aurora's lighting settings when Aurora is started or restarted

### Actual Behaviour
On startup (or restart), I have to manually go into Settings -> Device Manager and click Start for Corsair (this is the only device I am using). As seen in the screenshot below, none of the devices are started by default.

![2023-12-06_18-05-34](https://github.com/Aurora-RGB/Aurora/assets/5715576/8d7033ab-6ea4-4a2e-ae8d-4505b860cbcb)

### Reproduction steps
Happens on every startup

### Frequency
Every time

### Aurora Version:
v169

### Previously an Issue?
No

**Comment by Aytackydln** [comment]
You've been stuck on the old version. Update to the latest version manually by downloading zip or installer

**Comment by tcutchi** [comment]
I see

Downloaded and installed v198, will update or resolve issue tomorrow.

Thanks!

**Comment by tcutchi** [comment]
V198 seems to be working as intended!
Closing as resolved.
