### ISSUE TITLE
Entire app hangs briefly before switching to dark mode

### ISSUE THREAD

**Issue by D3SL** [Aurora-RGB/Aurora#185]
### Expected Behaviour
App should either start in dark mode or switching should be seamless on load

### Actual Behaviour
The first time opening the UI after boot the app opens in light mode and will hang for several seconds before switching to dark mode

### Reproduction steps
Have a dark windows theme on win10, turn on the computer, open Aurora

### Frequency
First open after boot

### Aurora Version:
V194

### Previously an Issue?
I believe it's been an issue since a dark theme was added.

**Comment by Aytackydln** [comment]
Thanks, fixed this in the latest pre-release
