### ISSUE TITLE
CPU Temperature Always Reporting 0

### ISSUE THREAD

**Issue by iLionheart** [Aurora-RGB/Aurora#186]
[sensors.txt](https://github.com/Aurora-RGB/Aurora/files/13628960/sensors.txt)

### Expected Behaviour
CPU Temperature reports the temperature recorded from the sensor.

### Actual Behaviour
CPU Temperature always reports 0degrees.

### Reproduction steps
1. Create a Percent (Gradient) Layer
2. Set the Current Value to LocalPCInfo/CPU/Temperature
3. Set the Maximum Value to 90 (or another non-zero number)
4. Set the Effect Type to "All at once"
     - Blink Threshold is a non-factor

The CPU in question is a Ryzen 7 5800x.

### Frequency
This happens every time. 

### Aurora Version:
Aurora v198

### Previously an Issue?
Yes, I have tried it in v194 and v129 and it did not work in either of them.

**Comment by Aytackydln** [comment]
Thanks, fixed in last version
https://github.com/Aurora-RGB/Aurora/releases
