### ISSUE TITLE
Error while updating light effects: Unable to cast object of type...

### ISSUE THREAD

**Issue by evan-baron** [Aurora-RGB/Aurora#188]
### Expected Behaviour
Radial gradient wave animation should work

### Actual Behaviour

![image](https://github.com/Aurora-RGB/Aurora/assets/128563152/127bd119-98e5-4786-a2de-e5a23b7832c9)

### Reproduction steps
Create new layer
Select Layer type: Gradient
Click on Gradient
Select Radial Gradient Brush
Change Animation Type: (Radial only) Zoom in
Move Wave Size: (any value)

### Frequency
Every time.

### Aurora Version:
v207

### Previously an Issue?
Don't know

**Comment by Aytackydln** [comment]
Thanks, fixed the error with latest pre-release but don't have time for the correct effect for now
