### ISSUE TITLE
Wallpaper Engine detecting Aurora as "Playing Audio" despite complete silence from the program

### ISSUE THREAD

**Issue by RealSourceOfficial** [Aurora-RGB/Aurora#189]
## Expected Behaviour
Wallpaper Engine being able to play audio (e.g. from videos, scenes, apps, ect) while Aurora is running in the background and sound is set to "Mute" when "Other Application Playing Audio"

## Actual Behaviour
Wallpaper Engine cuts out sound when Aurora is open, despite the program playing no sound. Works perfectly fine without Aurora open.

###Reproduction steps

1. Open Wallpaper Engine
2. Select Wallpaper with Audio features
3. Ensure volume is up
4. Go to Settings -> General and set "Other Application Playing Audio" to "Mute"
5. Ensure wallpaper plays audio
6. Open Aurora

## Frequency
Every time.

## Aurora Version:
(Aurora will no longer launch for some reason. Unsure of the issue, but it is NOT due to this bug report. Should be latest as of Friday, January 12th, 2024, as I had an auto-update prompt that updated the software, however I cannot verify if the update was applied as the application no longer opens. This issue was present before updating, as well.)

## Previously an Issue?
Yes.

**Comment by Aytackydln** [comment]
V206 had a problem if you updated it from V205. You can install V207 manually to fix the launch problem

**Comment by RealSourceOfficial** [comment]
It seemed to have fixed itself this morning... To be fair, I forgot to try restarting and windows auto updated last night so that's what did it most likely

**Comment by Aytackydln** [comment]
Aurora appears in the mixer when audio device is subscribed for Audio Layer's processing. I currently don't know how I can prevent that completely but I've delayed the subscription to hide it until Audio Layer needs it
