### ISSUE TITLE
Lighting doesn't start until any device setting gets changed

### ISSUE THREAD

**Issue by xamionex** [Aurora-RGB/Aurora#190]
### Expected Behaviour
On aurora start/startup it should start with my profile and show the effects for my profile

### Actual Behaviour
Aurora starts and it cycles red/transparent indefinitely whilst the program shows only white/blank

### Reproduction steps
I'm not sure if this is caused by making a new profile other than default. It just randomly started happening

1. Start Aurora, Lighting is blank
2. Change any setting in Devices and Wrappers, it starts

### Frequency
Every aurora startup

### Aurora Version:
v207

### Previously an Issue?
I'm new to aurora so I'm not sure if it's the case on previous versions

### Additonal Info
Before changing anything\
![image](https://github.com/Aurora-RGB/Aurora/assets/57235791/496e6efb-e008-4917-a0e6-f8a3aa4e57d1)
After setting example Preferred Keyboard Layout to International\
![image](https://github.com/Aurora-RGB/Aurora/assets/57235791/9aeb6192-c5c3-4c4c-83e2-cb7cd7c845aa)

**Comment by xamionex** [comment]
Logs If needed\
[Devices-2024-01-12 23.55.40.log](https://github.com/Aurora-RGB/Aurora/files/13926816/Devices-2024-01-12.23.55.40.log)
[2024-01-13 05.55.04.log](https://github.com/Aurora-RGB/Aurora/files/13926817/2024-01-13.05.55.04.log)
Note: The time I posted this is 06:02

**Comment by xamionex** [comment]
Verbose logs after last comment (same reproduction steps)\
[2024-01-13 06.03.40.log](https://github.com/Aurora-RGB/Aurora/files/13926822/2024-01-13.06.03.40.log)

**Comment by Aytackydln** [comment]
Hopefully fixed with last pre-release:
https://github.com/Aurora-RGB/Aurora/releases

**Comment by xamionex** [comment]
Fixed, thank you!
