### ISSUE TITLE
Gradient animated layer not saving 

### ISSUE THREAD

**Issue by iimma** [Aurora-RGB/Aurora#197]
### Expected Behaviour
After i reopened aurora, the gradient layer with animation config that i've set previously, should be there

### Actual Behaviour
Every time i reset aurora the colours i choose on the gradient layer in desktop settings are gone, and i have to choose them again and again

### Reproduction steps
Just create a gradient layer, press set to rainbow seamless and change some colours,  animation effect translate x/y and -4 effect angle

### Frequency
Every time i reset aurora

### Aurora Version:
Latest one, but has been hapening for a while now

### Previously an Issue?
Yes

**Comment by Aytackydln** [comment]
I'm still trying to figure out why this doesn't work for some people. Does the gradient colors reset to certaing colors every time or it just doesn't save?

**Comment by iimma** [comment]
They reset to 2 colors, both white, fully transparent and one on every side

**Comment by Aytackydln** [comment]
Can you tell me the language/locale of your computer?

**Comment by iimma** [comment]
Language is Argentinian Spanish. 
I would try that but i dk how to install it, im on w11.
If you can explain to me how to do it ill try it

**Comment by iimma** [comment]
Nevermind im installing v220 from the updater

**Comment by iimma** [comment]
its working now... The window movement is still laggy but at least i can save my gradient layers, thank you

**Comment by iimma** [comment]
It saved it the first time, but now i'm having the same issue but with a new one, now aurora crashes from time to time

**Comment by iimma** [comment]
[2024-03-04 23.21.58.log](https://github.com/Aurora-RGB/Aurora/files/14488313/2024-03-04.23.21.58.log)

**Comment by iimma** [comment]
![0460404c4835d0b7333781e4178aeff8](https://github.com/Aurora-RGB/Aurora/assets/30970464/38791e6d-c1ee-4253-831a-6a3f08880233)

**Comment by iimma** [comment]
i updated the bios to last one and now it seems to be working fine, idk, i hope it will last

**Comment by Aytackydln** [comment]
Okay, if it happens again please share your %appdata%/Aurora folder with me so I can look in to your profiles to see what might cause it
