### ISSUE TITLE
Helldivers 2

### ISSUE THREAD

**Issue by xamionex** [Aurora-RGB/Aurora#200]
Please add support for the following game:

**Game Name:**  Helldivers 2
**To be clear:** I'm not asking for support in the app, the game has recently went under a patch and for some reason is flagging Aurora as a cheat. I'm assuming this is due to cheaters having something called aurora? Because [when I googled this](https://www.google.com/search?q=helldivers+2+aurora) I got results from CH

GameGuard is flagging Aurora as a cheat and I can't play the game whilst Aurora is running

**Comment by Aytackydln** [comment]
I've added the game to the "Blacklist list" in Aurora to close Aurora when game opens but the game doesn't let Aurora detect the game is opened.

I've added the game's crash handler exe to the list. Hopefully this will help. I will try changing Aurora's exe name in the future

**Comment by Aytackydln** [comment]
This is resolved on latest pre-release version.
