### ISSUE TITLE
Request for Steelseries Apex 7 support

### ISSUE THREAD

**Issue by Water-Cat1** [Aurora-RGB/Aurora#201]
Please add support for the following device:

**Device Name:** SteelSeries Apex 7

**Device Website:** https://steelseries.com/gaming-keyboards/apex-7?switch=red

Currently works best through generic keyboard (preferred keyboard: none), however the ? and the ` keys cant seem to be controlled and stay locked to their previous colour. I did try the currently supported steelseries layouts however the closest one, Apex M750, results in the steelseries (APP/FN key) also becoming disabled.

OpenRGB appears to have support for this keyboard already, and I have it installed, but I do not use it for my keyboard lighting. I am specifically using Aurora to steelseries GG direct.

**Comment by Aytackydln** [comment]
Did you try different "Preferred Keyboard Layout" options?
Also that part is a bit bugged and some selections may need restart of Aurora to work best

**Comment by Water-Cat1** [comment]
United States is what matches my layout correctly. However I have run through others and it still makes no difference. I have also gone through all the keyboard layouts too, with no luck. In all cases the "?" and "~" keys still fail to be recognized.

Trying the RGB.net device seems to have all keys light up including the steelseries one. But then no further animation, just what the initial setting was.
OpenRGB works fine except the steelseries key and I do have to disable any lighting via SteelSeriesGG or it will flicker between them.

I don't know if this is any help but the below is what appears in the RGB.net remapper (although no remaping can be done)
![image](https://github.com/Aurora-RGB/Aurora/assets/10862949/dc00b0e6-80ce-44e3-87a6-b91de0532d30)
![image](https://github.com/Aurora-RGB/Aurora/assets/10862949/a18a73a3-e77b-46a8-8023-4c20832658cb)

**Comment by Water-Cat1** [comment]
Revisiting this I have managed to get openRGB working by remapping the steelseries key to the app key for the layout, and this seems to work with having all keys light up now.
![image](https://github.com/user-attachments/assets/4bb0b5a4-820e-4f52-8df6-6fbe1b326b0b)
I also noticed that the steelseries (rgb.net) also works with all keys by default and animates, although that one also makes the mouse bright orange for some reason. openRGB does not support the rival 5 yet (despite an issue with all the info seemingly open for a year now).

**Comment by Aytackydln** [comment]
looking at the screenshot, you are on outdated version. An old version had updater issue. You should update Aurora manually

**Comment by Water-Cat1** [comment]
Will be doing that. on an older version currently that has everything working i want. Latest version doesnt have official support, but likely i can do the same adjustment to get it to work.

**Comment by Aytackydln** [comment]
what is the removed feature?

**Comment by Water-Cat1** [comment]
I am currently sitting at v266 due to the Elite Dangerous profile not working after that version https://github.com/Aurora-RGB/Aurora/issues/237

**Comment by Water-Cat1** [comment]
Thanks to recent updates I am now on the latest version. 
Using the Apex M750 layout it now seems that all keys function correctly without remapping. I am using openRGB, but the steelseries devices seem to work as well - just that they also try to control the mouse I have as it is also steelseries (not supported by anything)

Happy for this on to be considered closed
