### ISSUE TITLE
Autoupdate from v194 failed with directory error

### ISSUE THREAD

**Issue by D3SL** [Aurora-RGB/Aurora#202]
### Expected Behaviour
Autoupdate should Just Work(TM)

### Actual Behaviour
About half-way through the process stopped with an error stating `AuroraDeviceManager/CroccatTalkWrapper/ is inaccessible` and asking the user to close Aurora. Closing aurora didn't make a difference. Downloading the installer for the new release worked fine.

### Reproduction steps
Unknown. 

### Frequency
Unknown

### Aurora Version:
V194

### Previously an Issue?
Not applicable.

**Comment by SpeedHighway** [comment]
I've run into this same blocker.  Deleting the folder, and re-attempting doesn't help, either.  It looks like the previous location was simply `CroccatTalkWrapper`, rather than `AuroraDeviceManager/CroccatTalkWrapper`.

**Comment by Aytackydln** [comment]
Sorry, the zip library changed in the Github machines. Unzipping is fixed after v194.
For a month or so I've zipped and uploaded new releases myself to fix this then stopped after a while.

Please use the last version's installer.
