### ISSUE TITLE
GTA V patch results in bad image

### ISSUE THREAD

**Issue by WB201304** [Aurora-RGB/Aurora#203]
After patching GTA V, when launching I recieve this error message.

GTA5.exe - Bad Image
---------------------------
C:\Program Files\LGHUB\sdks\sdk_legacy_led_x64.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc000012f. 

[Devices-2024-03-24 10.31.07.log](https://github.com/Aurora-RGB/Aurora/files/14735160/Devices-2024-03-24.10.31.07.log)
[2024-03-24 10.31.02.log](https://github.com/Aurora-RGB/Aurora/files/14735161/2024-03-24.10.31.02.log)

Edit: Forgot to mention I'm using the Logitech G915 TKL and G502 Lightspeed

**Comment by Aytackydln** [comment]
GTA integration doesn't work right now.

You should delete the patch until it is fixed

**Comment by Aytackydln** [comment]
You can just disable GTA5 profile in Aurora as you can just use Lightsync profile with it
