### ISSUE TITLE
Aurora v229 crashes with Logitech GHUB running

### ISSUE THREAD

**Issue by Froasl** [Aurora-RGB/Aurora#205]
Log when launching fine: [2024-03-31 09.43.06.log](https://github.com/Aurora-RGB/Aurora/files/14814976/2024-03-31.09.43.06.log)
Log when crashing: [2024-03-31 09.53.29.log](https://github.com/Aurora-RGB/Aurora/files/14814975/2024-03-31.09.53.29.log)
Device log, generated rarely, from the same launch as the log when crashing: [Devices-2024-03-31 11.53.47.log](https://github.com/Aurora-RGB/Aurora/files/14814969/Devices-2024-03-31.11.53.47.log)
(Operating system in logs is incorrect, I'm actually using Windows 11 Pro)

### Expected Behaviour
Aurora should launch.

### Actual Behaviour
Aurora crashes effectively immediatly on launch, within a few seconds. When it does, it will open multiple error windows.
Most of the time, it will keep opening these windows, about one per second, although rarely it will stop after 2 windows. As far as I can tell, there are only 2 different error messages, which can both occur on the same crash.
![image](https://github.com/Aurora-RGB/Aurora/assets/41173356/7964df14-d738-4119-8087-5eb261f5dea2)
![image](https://github.com/Aurora-RGB/Aurora/assets/41173356/ace2a8cf-1be2-48d5-ae78-5dd05e9691c0)

As long as the error messages are not clicked, Aurora will keep updating the keyboard, but with a significant delay and very low refresh rate. When they are closed, either through clicking OK or through the X in the title bar, keyboard lighting will freeze and Aurora will close soon after.
When it does not crash, Aurora appears to work perfectly.

### Reproduction steps
Have Logitech GHUB running at the same time as Aurora. It does not matter which is started first. 

### Frequency
Problem occurs most of the time, but not always. Aurora will consistently launch or crash unless GHUB is restarted.

### Version:
Aurora v229, started immediately after updating through the automatic updater.
GHUB version 2024.2.534136, not updated recently.
Windows 11 Pro, version 10.02631 Build 22631, updated before updating Aurora, although before updating Aurora launched without issues once.

### Previously an Issue?
No.
Aurora did sometimes fail to initialize Logitech RGB.NET, usually when waking the PC from sleep, which would necessitate a restart of GHUB, but this would never crash Aurora.

**Comment by Aytackydln** [comment]
I made a new pre-release with the fix

**Comment by Froasl** [comment]
I updated to v230, it is still crashing. It seems like now there is only an InvalidOperationException
Log: [2024-03-31 15.16.18.log](https://github.com/Aurora-RGB/Aurora/files/14816485/2024-03-31.15.16.18.log)

**Comment by Aytackydln** [comment]
Published another release

Also, thank you for testing the beta version

**Comment by Froasl** [comment]
It seems the original issue has been fixed, but now it crashes most times, but not always, with
```
System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.MethodBaseInvoker.ThrowTargetParameterCountException()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
It also does this without GHUB running.
Crash: [2024-04-01 06.34.25.log](https://github.com/Aurora-RGB/Aurora/files/14820305/2024-04-01.06.34.25.log)
No crash:[2024-04-01 06.34.07.log](https://github.com/Aurora-RGB/Aurora/files/14820306/2024-04-01.06.34.07.log)

To be honest, I didn't intentionally beta test, I only enabled pre-release downloads for one patch, and never turned it off. But I will keep it turned on, it is the least I could do for such a great piece of software.

**Comment by Aytackydln** [comment]
Was there any errors while updating?

Also can you try reinstalling Aurora? This looks like some files are not updated to me

**Comment by Froasl** [comment]
No errors while updating, except the one when Aurora launched after the update, and reinstalling didn't fix it. I also tried deleting the `%appdata%\Roaming\Aurora` folder, which also did not affect the crash.
I did compare the files before and after reinstalling, but it doesn't seem like any files were missing or different in the old install
```
Only in Aurora_old/Aurora: Aurora.dll.config
Only in Aurora_old/Aurora: Aurora.sys
Only in Aurora_old/Aurora/AuroraDeviceManager: Wooting.NET.dll
Only in Aurora_old/Aurora/AuroraDeviceManager: mscordaccore_amd64_amd64_8.0.123.58001.dll
Only in Aurora_old/Aurora/AuroraDeviceManager: mscordaccore_amd64_amd64_8.0.224.6711.dll
Only in Aurora_old/Aurora: AuroraRgb.sys
Only in Aurora_new/Aurora: unins000.dat
Only in Aurora_new/Aurora: unins000.exe
Only in Aurora_old/Aurora: unins001.dat
Only in Aurora_old/Aurora: unins001.exe
```
Another thing I noticed and might mention, when crashing AuroraDeviceManager.exe will keep running in the background and, according to GHUB, is still actively controlling my device lights, although it does stop updating things like CPU usage or shortcuts assists.

**Comment by Aytackydln** [comment]
Sorry that log doesn't help me much. I've improved exception logs with v232. Hopefully it can tell me what is actually causing it

**Comment by Froasl** [comment]
Crash: [2024-04-02 04.37.23.log](https://github.com/Aurora-RGB/Aurora/files/14831698/2024-04-02.04.37.23.log)
No crash: [2024-04-02 04.45.14.log](https://github.com/Aurora-RGB/Aurora/files/14831697/2024-04-02.04.45.14.log)

The error in line 17 is caused by AuroraDeviceManager still running in the background with that logfile open. When I manually kill it before launching Aurora, that error goes away, but it still crashes.

**Comment by Aytackydln** [comment]
can you test v233?
https://github.com/Aurora-RGB/Aurora/releases

**Comment by Froasl** [comment]
I missed v233 so auto-updated to v234 directly, and it still crashes. Log doesn't seem different, but I might as well include it: [2024-04-03 07.15.01.log](https://github.com/Aurora-RGB/Aurora/files/14848281/2024-04-03.07.15.01.log)
BTW, I did join the discord server, if you'd like to try something where 1 or 2 replies per day isn't quite enough, feel free to message me

**Comment by Aytackydln** [comment]
I figured out what can cause this error, but I don't see it anywhere in the code. How often and when does it happen/

**Comment by Aytackydln** [comment]
Thanks, that description helped. 

Please test v235 and I will make it a full release if you don't have any problems

**Comment by Froasl** [comment]
So far it is working fine. Thank you for your work.
