### ISSUE TITLE
last version lagging hard

### ISSUE THREAD

**Issue by djackerick** [Aurora-RGB/Aurora#206]
### Expected Behaviour

widow should move fluently

### Actual Behaviour

window lags terribly when moving

### Reproduction steps

- open
- move window

### Frequency

every time

### Aurora Version:

231
### Previously an Issue?

no

yesterday version worked correctly, after updating to v231 happened what is shown in the video

https://youtu.be/ihPaitQq_e4

after rebooting problem persists 

i'm going back to some previous version for now

**Comment by Aytackydln** [comment]
do you have any logs with that version?

**Comment by djackerick** [comment]
how are that logs filenames called?
