### ISSUE TITLE
Aurora crashes when adding boolean "Numeric State Variable" in conditional override

### ISSUE THREAD

**Issue by Froasl** [Aurora-RGB/Aurora#207]
### Expected Behaviour
I should be able to add the boolean "Numeric State Variable" to any layer property which accepts a boolean.

### Actual Behaviour
When adding the "Numeric State Variable" Aurora crashes, opening multiple identical error windows. The non-boolean "Numeric State Variable" does not crash. After restarting, the lighting profile selector on the left will sometimes contain duplicate profiles (e.g. 2 or more desktop profiles), in seemingly random order, though these all reference the same profile. It reset to normal after a few restarts.
Log: [2024-04-10 12.04.37.log](https://github.com/Aurora-RGB/Aurora/files/14931989/2024-04-10.12.04.37.log)

### Reproduction steps
Open the conditional override for any layer on any profile (tested desktop and better discord, both regular and overlay layers), enable "Dynamic Value" override, select a property which accepts a boolean, then insert "Numeric State Variable".

### Frequency
Every time.

### Aurora Version:
v235

### Previously an Issue?
Don't know, I haven't used it before.

**Comment by Aytackydln** [comment]
This is fixed with latest version. Thanks for reporting
