### ISSUE TITLE
Process Monitor having major launch issues

### ISSUE THREAD

**Issue by YOUNGBLOOD428** [Aurora-RGB/Aurora#209]
### Expected Behaviour
Aurora should boot normally.

### Actual Behaviour
Aurora opens a crash message, however Aurora does remain functional except for controlling RGB devices and everything involving the Process Monitor. Crash message contains the error within the attached image.

![Aurora Error](https://github.com/Aurora-RGB/Aurora/assets/168951594/853d6211-c73f-4f1c-ba98-462ccfca9d23)

### Reproduction steps
Attempt to boot Aurora, like how you normally would, and that error should appear shortly after.

### Frequency
Every time, even after reboots, uninstalls, and AppData deletion

### Aurora Version:
V239

### Previously an Issue?
Yes, maybe about 3 or 5 updates ago or so.

Log of my latest launch attempt:
[2024-05-05 05.13.48.log](https://github.com/Aurora-RGB/Aurora/files/15211846/2024-05-05.05.13.48.log)

**Comment by Aytackydln** [comment]
This isn't fault of Aurora but can be added as a warning when this happens

Folow the instructions here to fix it:
https://stackoverflow.com/a/6930421/13320838

**Comment by YOUNGBLOOD428** [comment]
Worked like a charm, everything is now fully functional!

Suppose something important corrupted when my pc crashed and was greeted with that.

Anyway, thanks for you your time and help!
