### ISSUE TITLE
v248 Opens with blank UI

### ISSUE THREAD

**Issue by SpeedHighway** [Aurora-RGB/Aurora#212]
### Expected Behaviour

The application should start up, and profiles should display, along with functionality enabling.

### Actual Behaviour

The application opens with a blank, red, UI.  It has no profiles, and nothing in the UI can be clicked except the eyeball at the bottom-left.
The event viewer displays an application error stating: 
- Source: PerfProc
- EventID 2002
- Message: Unable to open the job object \BaseNamedObjects\WmiProviderSubSystemHostJob for query access. The calling process may not have permission to open this job. The first four bytes (DWORD) of the Data section contains the status code.
The log file (not the devices log) stops at "Waiting for modules..." and never proceeds.

### Reproduction steps

Install v248
Attempt to start the application.  Double-click on the Taskbar icon to run it, or use the context menu.
Note: The application already starts using UAC, but I attempted to specifically run as admin, just in case, with no change.
Note: Attempting to exit the application results in a completely stalled UI.

### Frequency

Every time, including after killing all processes, multiple times.

### Aurora Version:

v248

### Previously an Issue?

No, and rolling back to v247 resolved the issue.

**Comment by Aytackydln** [comment]
please send the logs

**Comment by vincent-aubert-it** [comment]
Same problem here.

Logs:

```
Aurora-2024-05-22 00:22:31.115 [INF] 
========================================
Operation System: Windows 10 Pro
Environment OS Version: Microsoft Windows NT 10.0.22631.0
System Directory: C:\WINDOWS\system32
Executing Directory: C:\Program Files\Aurora
Launch Directory: C:\Program Files\Aurora
Processor Count: 16
Environment Version: 8.0.4
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: v248
========================================
Aurora-2024-05-22 00:22:31.125 [INF] Loading Configuration
Aurora-2024-05-22 00:22:31.334 [INF] Loading Input Hooking
Aurora-2024-05-22 00:22:31.335 [INF] Loading Device Manager...
Aurora-2024-05-22 00:22:31.460 [INF] Loaded Input Hooking
Aurora-2024-05-22 00:22:31.462 [INF] Fetching latest pointers
Aurora-2024-05-22 00:22:31.462 [INF] Starting IpcListener
Aurora-2024-05-22 00:22:31.464 [INF] Initializing Lightsync...
Aurora-2024-05-22 00:22:31.467 [INF] Loading RazerSdkManager
Aurora-2024-05-22 00:22:31.469 [WRN] Currently installed razer sdk version "0.0.0" is not supported by the RazerSdkManager!
Aurora-2024-05-22 00:22:31.469 [INF] Loading Plugins
Aurora-2024-05-22 00:22:31.473 [INF] Loading Applications
Aurora-2024-05-22 00:22:31.475 [INF] Loaded Plugins
Aurora-2024-05-22 00:22:32.271 [INF] [IPCServer] Pipe created {}
Aurora-2024-05-22 00:22:32.272 [INF] [AuroraCommandsServerIPC] Pipe created {}
Aurora-2024-05-22 00:22:32.272 [INF] Listening for wrapper integration calls...
Aurora-2024-05-22 00:22:32.280 [INF] Loaded Device Manager
Aurora-2024-05-22 00:22:32.281 [INF] Loading KB Layouts
Aurora-2024-05-22 00:22:33.499 [INF] Loading ConfigUI...
Aurora-2024-05-22 00:22:33.499 [INF] LGS Pipe name: LGS_LED_SDK-00000001
Aurora-2024-05-22 00:22:33.500 [INF] Initialized Lightsync
Aurora-2024-05-22 00:22:33.924 [INF] Waiting for modules...
```


![image](https://github.com/Aurora-RGB/Aurora/assets/63680418/10164428-2fe4-42a9-97ef-036f1da6c1f5)

**Comment by tnka1337** [comment]
same with v251

**Comment by Aytackydln** [comment]
Thanks, logs helped and I've just made a new release

**Comment by SpeedHighway** [comment]
![image](https://github.com/Aurora-RGB/Aurora/assets/6772686/db1f5865-b3cb-497d-820f-7f609b8aab25)
Can confirm that the UI is now once again functional, without having Chroma SDK installed, in v252.  
Thank you so much!
