### ISSUE TITLE
InvalidCastException on dynamic value opacity override

### ISSUE THREAD

**Issue by Codemonkey6658** [Aurora-RGB/Aurora#213]
### Actual Behaviour
Aurora throws a System.InvalidCastException when a layer property's opacity override is set to dynamic value as it tries to cast a double to a nullable single.
[2024-06-01 17.42.49.log](https://github.com/user-attachments/files/15522809/2024-06-01.17.42.49.log)

### Reproduction steps

Start Aurora and enable the opacity layer property override with the dynamic value override mode

### Aurora Version:

Error started at v257

### Previously an Issue?

No v256 and below don't have this error

**Comment by Aytackydln** [comment]
Fixed with v258
