### ISSUE TITLE
Crash with template

### ISSUE THREAD

**Issue by xamionex** [Aurora-RGB/Aurora#215]
![image](https://github.com/Aurora-RGB/Aurora/assets/57235791/8bb4cc7a-6a5a-473b-80c2-f5f267bd7cba)

Save this as template and crash happens:
![image](https://github.com/Aurora-RGB/Aurora/assets/57235791/7d54c9f5-1736-4180-bfdc-697680d33ead)

**Comment by Aytackydln** [comment]
I already made a fix for this and further creations of this shouldn't be a problem.

If it still happens reopen the issue and send me your %appdata%/Aurora folder
