### ISSUE TITLE
Chroma Issue since latest update changing chroma 

### ISSUE THREAD

**Issue by UniCizin** [Aurora-RGB/Aurora#217]
### Expected Behaviour (if not obvious)
chroma worked before like a charm with icue

### Actual Behaviour
since the last "big update referring to chroma", the functionality freezes after a couple of minutes.
F.E. i play Hunt:Showdown and at some point in the game the keyboard just freezes with the current color and resets when i quit hunt

### Reproduction steps
most current Aurora update, chrome connect and icue. 
Start a chroma game

### Aurora Version:
v264

### Previously an Issue?
worked like a charm for a long time

**Comment by Aytackydln** [comment]
This does not happen for me. Can you try adding a layer that constantly changes a key to Chroma profile? I want to know if every layers or just the chroma layer freezes

**Comment by UniCizin** [comment]
i think i figured it out.
i had a chroma layer in my desktop profile from earlier versions. and Hunt was a enabled process in the new chroma profile that came with the update. my suspicion is that they somehow competed with each other.
so now for testing i disabled my own chroma layer and excluded hunt frm the new chroma profile and gave the game a proper profile with chroma and stuff.

seems to work for now, will continue testing these days.

**Comment by Aytackydln** [comment]
Thanks. Chroma settings were reset for a version. That explains it

**Comment by UniCizin** [comment]
So this was not the issue . Seems Like Aurora looses Connection to Chroma or the sdk.
