### ISSUE TITLE
Restore application enabled checkboxes

### ISSUE THREAD

**Issue by Koyyle** [Aurora-RGB/Aurora#221]
This feature was removed with commit https://github.com/Aurora-RGB/Aurora/commit/ccaa67d50d3cd4ecc135e0bb28ce71d22ffd0bab, and I tried dealing with it, but it makes it difficult to have profiles that are overlay only. I specifically use it with the Better Discord profile to make it easier to tell if I'm muted or have notifications. 
If there's another way to do this and I'm just missing something, feel free to let me know!

**Comment by Aytackydln** [comment]
You can right click the profile pictures on the left

**Comment by Koyyle** [comment]
Ah, thank you! Sorry for creating an issue over that, then.

**Comment by Aytackydln** [comment]
No problem. I will add an explanation on the tooltips of profiles. This should help a little
