### ISSUE TITLE
Uniwill support removed

### ISSUE THREAD

**Issue by PenmanHsiung** [Aurora-RGB/Aurora#224]
Uniwill support have been accidently removed since v195
This cause Aurora stops working on XMG, Mechrevo, and some other Uniwill devices.
<img width="461" alt="v194" src="https://github.com/Aurora-RGB/Aurora/assets/98872461/87e60e50-e676-44af-87f8-e29fc2006cbf">
v194

<img width="461" alt="v195 and after" src="https://github.com/Aurora-RGB/Aurora/assets/98872461/909b01c3-6b06-4097-b9b3-000c8d53a47d">

v195 and after

#180 #219 seems to be the same problem

**Comment by Aytackydln** [comment]
I added back Uniwill device, though there's a small chance it may not work the same

https://github.com/Aurora-RGB/Aurora/releases/tag/v272

You can install this pre-release over.
For any reason, you backups will be at %appdata%/AuroraBackups
You can also manually backup your data at %appdata%/Aurora
