### ISSUE TITLE
Lenovo Legion Gaming 7 (Lenovo Vantage) Support

### ISSUE THREAD

**Issue by WalterWoshid** [Aurora-RGB/Aurora#231]
Please add support for the following device:

**Device Name:** Lenovo Legion Gaming 7

**Device Website:** https://download.lenovo.com/pccbbs/pubs/legion_pro7/html/html_en/explore_lightingEffects.html#t2

I'd love to join Discord and help reverse-engineer it :)

**Comment by Aytackydln** [comment]
Adding the support on OpenRGB would be better. They provide better help and it would benefit more users
