### ISSUE TITLE
Elite Dangerous profile no longer working

### ISSUE THREAD

**Issue by Water-Cat1** [Aurora-RGB/Aurora#237]
### Expected Behaviour (if not obvious)
Elite dangerous profile should have the keys light up according to keybinds and in game events.

### Actual Behaviour
Keyboard switches to profile on game start, but only shows default background colour.

### Reproduction steps
Launch Elite dangerous while Aurora is running. 

### Aurora Version:
v291. A fresh install of this version seemed to not produce a profile folder in %appadata% (along with many other profiles). Updating to this version keeps the files, but still breaks.

### Previously an Issue?
No. I still had the installation file for v225 and it works correctly on that version. I know that is many versions different so if i find time I will try narrow this down.

**Comment by Water-Cat1** [comment]
The issue happens between v266 and v267 - when the GSI prompt came in.

If I close the Aurora window while looking at the elite dangerous profile (from upgrading the version) i get the below error pop up.
![image](https://github.com/user-attachments/assets/1bd6e083-a94f-4cc5-9973-563cfc93e289)

The only profiles that seem to load on a fresh install is the below. Elite dangerous does not show if I do a completely fresh install.
![image](https://github.com/user-attachments/assets/90a545c0-fdfc-4601-b96f-c4b0aa58e1e6)

**Comment by Aytackydln** [comment]
Thanks for reporting. Released new version

**Comment by Water-Cat1** [comment]
Updated to v292. No issues in regards to having the profile appear. However, the profile does not function with the game. Only the background appears.
v292 
![image](https://github.com/user-attachments/assets/88b23035-e753-4de9-b82c-c84eae09a28a)

It should be appearing as it does below in v266:
![image](https://github.com/user-attachments/assets/b5644b9b-da34-4cf4-8074-417c8b110d28)

The profile highlights according to your current bindings (AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\Custom.4.0.binds) and should react to events in the journal of the game (C:\Users\%userprofile%\Saved Games\Frontier Developments\Elite Dangerous\Journal.*.log, and json files).

**Comment by Water-Cat1** [comment]
Can confirm with the latest update v293 that the profile is working again!
