### ISSUE TITLE
Pre-release v5 breaks Aurora on Uniwill device

### ISSUE THREAD

**Issue by PenmanHsiung** [Aurora-RGB/Aurora#24]
v5 version of Aurora stops functioning on my Uniwill device (more specifically, Mechrevo laptop with Uniwill 35X ANSI keyboard layout), and so does v6 & v9.
Rollback to v4 can make Aurora work again.

**Comment by Aytackydln** [comment]
Can you provide logs and behaviour?

Does your device get "Initialized"? Is there any color update even if once after initialize?

**Comment by PenmanHsiung** [comment]
Device Manager shows the device was initialized, but with a 0ms delay (normally if Aurora is correctly functioning, the delay should be about 40ms), stop and restart the devices couldn't solve the problem.

After initialization, no color update appeared——keyboard light just turned off.

If new version was installed with previous version of Aurora on, then the light just left motionless (lights still on, but animation effect stops), and attempt to re-initialize device just makes lights go off.

Here's the log (with pre-release v10)
[2022-02-05 21.45.33.log](https://github.com/Aurora-RGB/Aurora/files/8008118/2022-02-05.21.45.33.log)

**Comment by Aytackydln** [comment]
v14 is being built, can you check with that?

**Comment by PenmanHsiung** [comment]
Problem has been successfully fixed with v14, much appreciate!
