### ISSUE TITLE
Crashes when editing somethings

### ISSUE THREAD

**Issue by Sandman192** [Aurora-RGB/Aurora#241]
### Expected Behaviour (if not obvious)

For Download More Profiles it should open a browser for those Profiles.

### Actual Behaviour

Crashes when clicking on Reverse gradient stops from Percent Gradient (Liner only) in Volume Overlay
Crashes in Counter Strick with clicking on Add regular kills, Ad head shoot kills, or Reset kills.
Can't get the G19 logo to work at all.
Had a hard time getting anything to work. Nothing would respond when changing previews in game profiles. Then when I kept playing around with the slider and checkboxes under the "Preview tab" it particularly worked to all started working in American Truck Sim.
Minecraft on the other hand you can't stop the Burning or the low Rain Strength in Preview tab. All ways low and sliding it all the way to the right is still the same. Selecting In Game tuns all the top keys of the G kes, F1 to Pause and ~ to the - on the num pad and the rest all red exp for WASD and E, 5, shift, CRTL, and space. Regen overrides Wither and Poison. Absorption, Food, Armor, and Experience do nothing. At first scrolling Health only showed a single pink letter from left to right and at 100% health was not show at all but when messing with just the preview settings it started working.
In profiles when clicking on Download More Profiles just opens File Explorer.

### Aurora Version:

v302.

### Previously an Issue?

Yes

![Screenshot (62)](https://github.com/user-attachments/assets/8f2feff6-6132-4e30-9de6-c4bf554f76ab)
![Screenshot (61)](https://github.com/user-attachments/assets/07d17514-efd9-4627-a4f2-65936cadae82)
[2024-11-01 18.39.36.log](https://github.com/user-attachments/files/17606000/2024-11-01.18.39.36.log)
[2024-11-02 06.01.48.log](https://github.com/user-attachments/files/17606001/2024-11-02.06.01.48.log)
[2024-11-02 06.08.57.log](https://github.com/user-attachments/files/17606002/2024-11-02.06.08.57.log)
[2024-11-02 06.09.37.log](https://github.com/user-attachments/files/17606003/2024-11-02.06.09.37.log)

**Comment by Aytackydln** [comment]
Thanks

I fixed the problems you mentioned in a new pre-release build

**Comment by Sandman192** [comment]
Your pre-release is broken too.
I selected pre-release in the update tab then click on update now and nothing happen.
I restart Aurora and got this err message.
![image_2024-11-02_125551063](https://github.com/user-attachments/assets/8965d124-def1-411c-96f6-f7ce4b6ec59e)
