### ISSUE TITLE
Please add support for Logitech G913. The \(|) symbol and media keys on the G913 keyboard are not illuminated.

### ISSUE THREAD

**Issue by MistKear21** [Aurora-RGB/Aurora#244]
Please add support for the following device:

Device Name: Logitech G913

Device Website: https://www.logitechg.com/en-my/products/gaming-keyboards/g913-low-profile-wireless-mechanical-gaming-keyboard.html

**Comment by Aytackydln** [comment]
It's not possible with Logitech's SDK. You can use OpenRGB but you can't use per-game profiles with GHUB
