### ISSUE TITLE
Crash when Add Process to profile

### ISSUE THREAD

**Issue by Rosen01** [Aurora-RGB/Aurora#246]
### Expected Behaviour (if not obvious)
Selected process is added onto the profile.

### Actual Behaviour
Crash of the application. 
![Aurora_crash](https://github.com/user-attachments/assets/b2377a0a-4116-49d2-9d84-cb74d5848efd)

### Reproduction steps
1. select a profile
2. click on Add Process button
3. select a process (running or file selection)
4. click Add Profile button

### Aurora Version:
v313

### Previously an Issue?
Don't know

**Comment by Aytackydln** [comment]
Should be fixed with [v316](https://github.com/Aurora-RGB/Aurora/releases/tag/v316). Thanks
