### ISSUE TITLE
Program thinks GMMK is like a mouse

### ISSUE THREAD

**Issue by PrincessAkira** [Aurora-RGB/Aurora#32]
### Expected Behaviour
It should work on the keyboard :D
video: https://www.youtube.com/watch?v=bIGBr8f3X5k

### Actual Behaviour
It lights the Keyboard up as it would with my mouse 

### Reproduction steps
Get a EVisionKeyboard or a GMMK from Glorious

### Frequency
well everytime

### Aurora Version:
v21

### Previously an Issue?
no that i saw

**Comment by Aytackydln** [comment]
Since you are using OpenRGB things should be fine as long as OpenRGB led names are correct. You can check them on ORGB by toggling to LED View. If the led name is in the file below it can use the leds correctly, otherwise Aurora will map those lights to "Additional Light #"

https://github.com/Aurora-RGB/Aurora/blob/master/Project-Aurora/Project-Aurora/Devices/OpenRGB/OpenRGBKeyNames.cs

Also from what I see on google images the mouse layout is like Razer Mamba. Can you try that layout?

**Comment by PrincessAkira** [comment]
The Problem is tho that it doesnt work with my Keyboard.
It only works when it thinks its another Device.
This is kinda annoying

**Comment by Aytackydln** [comment]
What I know is, if Aurora doesn't know the leds from OpenRGB, it assumes those leds are "Peripheral Led". This is then OpenRGB problem. Your keyboard's led names are namen unconventionally

**Comment by PrincessAkira** [comment]
https://gitlab.com/CalcProgrammer1/OpenRGB/-/issues/1544
I mean this states the Board is detected

**Comment by Aytackydln** [comment]
So they left the keyboard like that... OpenRGB needs to have propert names for the leds, not led 1 led 2 etc.

Proper keyboard should look like this:
![image](https://user-images.githubusercontent.com/11393706/155338502-81a36671-8d04-46ec-abd4-54db5b9bf8f3.png)

**Comment by PrincessAkira** [comment]
hmm.
How should we continue this then?
Any ways to contact them, since i dont have a Gitlab for example.

**Comment by diogotr7** [comment]
Evision boards shouldn't work at all. The firmware on them does not support Direct mode. If you override the direct mode check you will wear out the flash on the keyboard quickly. Look into [SonixQMK](https://github.com/sonixqmk)

**Comment by PrincessAkira** [comment]
> Evision boards shouldn't work at all. The firmware on them does not support Direct mode. If you override the direct mode check you will wear out the flash on the keyboard quickly. Look into [SonixQMK](https://github.com/sonixqmk)

Would this from Calc also work?
https://i.reddit.com/r/glorious/comments/pytfsn/unofficial_qmk_firmware_for_gmmk_full_nonpro/
its literally for a gmmk.
Since The GMMK TKL should use the same chips as the GMMK Pro, which has QMK Support.
![image](https://user-images.githubusercontent.com/45071533/155360950-af4a3592-b330-46ba-90df-207d7c2cbe9d.png)

**Comment by PrincessAkira** [comment]
> Evision boards shouldn't work at all. The firmware on them does not support Direct mode. If you override the direct mode check you will wear out the flash on the keyboard quickly. Look into [SonixQMK](https://github.com/sonixqmk)

Ill try and check that out.
Im using a GMMK TKL so ill give it a shot.
