### ISSUE TITLE
Full changelog link at bottom of latest release doesnt work correctly

### ISSUE THREAD

**Issue by Masamune3210** [Aurora-RGB/Aurora#38]
### Expected Behaviour

Link should point to a list of all activity between the two points
### Actual Behaviour

Seems either GitHub cant figure out what happened with the version numbers or something else is broken
### Reproduction steps

Click the Full Changelog: link at the bottom of the v26 release (latest as of post)

**Comment by Aytackydln** [comment]
Sorry, I adited that part manually. Fixed it now

**Comment by Masamune3210** [comment]
Wasn't super tore up about it, just a issue was the best way to let you know I figured. Love the program so glad to help out in whatever little ways I can!
