### ISSUE TITLE
v40 possible memory leak

### ISSUE THREAD

**Issue by mattnoir** [Aurora-RGB/Aurora#46]
Just after around 3 minutes of running, RAM usage went to 3GB and still goes up. Did not have this issue in the previous version

Not sure what info is needed. For now downgrading to v38

**Comment by Aytackydln** [comment]
Hi, thanks for letting me know. Can you tell me which layers you are using?

**Comment by mattnoir** [comment]
Hi again,
I am basically using this profile:
https://modworkshop.net/mod/24780
with slight modifications - disabled mic and audio layers and changed colors to resemble aurora instead of plasma

my keyboard is Logitech G513 and mouse is Logitech G502
I am using g hub (hate the overwrite issue upon wake up, but whatever)

**Comment by Masamune3210** [comment]
Just had this happen to be, memory usage was around 3 GB before resource reaper took out my entire system almost just to make room

**Comment by Masamune3210** [comment]
![image](https://user-images.githubusercontent.com/1053504/169069345-29058e47-3c47-4a86-b30e-e0137e1b087c.png)

**Comment by Masamune3210** [comment]
Razer BlackWidow Elite, Razer Naga Trinity

**Comment by Aytackydln** [comment]
I am very sorry this happened. I will also test various profiles before making releases now. I didn't have this issue on my end because I have optimized the layers I use.

I've fixed this in the latest build
