### ISSUE TITLE
support for Hyperx Alloy Origins with abnt layout pls

### ISSUE THREAD

**Issue by Rafaelh9siX** [Aurora-RGB/Aurora#47]
Please add support for the following device with abnt layout:

**Device Name:** Hyperx Alloy Origins 

**Device Website:** https://hyperx.com/products/hyperx-alloy-origins-mechanical-gaming-keyboard?variant=42330451148957

**Comment by Rafaelh9siX** [comment]
It currently works using the configuration for hyperx alloy elite, but typing "?" and "fn" do not light up

**Comment by Aytackydln** [comment]
I guess you can choose any other layout with an Fn key. 

About Fn key not lighting up when yuou press it. Aurora can't detect that key is being pressed. There is nothing I can do about that

**Comment by Aytackydln** [comment]
Even when you choose a layout with Fn key? If so, can you share me your keyboard layout in OpenRGB? I need to how that key is named

**Comment by Rafaelh9siX** [comment]
![image](https://user-images.githubusercontent.com/13911123/169718954-3ffaab20-2404-43b6-97f0-b830793ec0ff.png)
![image](https://user-images.githubusercontent.com/13911123/169718965-81270f8b-383b-48d5-abd6-44c555a30853.png)
Is that what you need?

**Comment by Rafaelh9siX** [comment]
![image](https://user-images.githubusercontent.com/13911123/169719006-da773a4d-34f0-4f37-9624-b34882dedf5e.png)

**Comment by Aytackydln** [comment]
Top image is what I wanted. Can you click the Fn key and show me what it says on "LED: [Key: XXXX]"?

**Comment by Rafaelh9siX** [comment]
![image](https://user-images.githubusercontent.com/13911123/169899661-2c723534-e98a-4f50-8875-5f3922be5bf9.png)

**Comment by Aytackydln** [comment]
Okay, for the Fn key you can use Asus Strix Scope layout. For the ? key I need to make a patch

**Comment by Rafaelh9siX** [comment]
Ok, ty for the attention
