### ISSUE TITLE
stops working after awhile

### ISSUE THREAD

**Issue by azumukupoe** [Aurora-RGB/Aurora#50]
### Expected Behaviour

keep working until quit
### Actual Behaviour

stops working after awhile
tray icon becomes unresponsive, have to quit from task manager
### Reproduction steps

for me, it just happens
### Frequency

everyday
### Aurora Version:

v41
### Previously an Issue?

Yes

[2022-05-25 19.46.00.log](https://github.com/Aurora-RGB/Aurora/files/8778351/2022-05-25.19.46.00.log)

**Comment by Aytackydln** [comment]
can you share your profile with me? Logs don't show anything sadly

**Comment by azumukupoe** [comment]
I'm only using the default desktop profile

**Comment by Crapy** [comment]
Happens to me as well, usually after the computer wakes up from sleep.

**Comment by Aytackydln** [comment]
I've tried to solve this before and I couldn't. I hope someone with better experience can solve this one :(

**Comment by Aytackydln** [comment]
Sorry I've not been able to check this issue. Usually how long does it run before Aurora closes?
Can you check the latest version, it had small improvements with window handles

**Comment by Aytackydln** [comment]
can you try this fix?
https://github.com/Aurora-RGB/Aurora/issues/63#issuecomment-1200134725

**Comment by Aytackydln** [comment]
Okay then can you show me event log from "Event Viewer" like the guy from that thread? Right after aurora closes

https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/

**Comment by Aytackydln** [comment]
can you try latest dev version?

**Comment by Aytackydln** [comment]
This is an error that's source can't be found easily. I remember much earlier I made a workaround fix for someone else

open %appdata%/Aurora and edit Config.json and change "close_on_exception" value to false and you won't be bothered with the error again but Aurora might become unstable
