### ISSUE TITLE
Glitch Layer Use Freestyle not working

### ISSUE THREAD

**Issue by MercAngel** [Aurora-RGB/Aurora#51]
### Expected Behaviour
Use Freestyle to select all keys (LayerType Glitch)

### Actual Behaviour
Use Freestyle does not work have to assign keys (LayerType Glitch)

### Reproduction steps
Remove Assign keys select Use Freestyle draw box around keyboard nothing happens Freestyle work with other layers

### Frequency
every time

### Aurora Version:
v43
### Previously an Issue?
do not know was useing v41

**Comment by Aytackydln** [comment]
I've made a fix in the latest pre-release build
