### ISSUE TITLE
Logitech sdk stops working after computer sleep

### ISSUE THREAD

**Issue by Crapy** [Aurora-RGB/Aurora#55]
I am using the screen sample layer on my keyboard and my mouse (G502) and it appears to stop working after the computer goes to sleep and wakes up, the keyboard continues to work (Ducky One RGB 2), i've looked at the Device Manager and it appears that logitech is stopped there after the computer wakes up, pressing start does not work and you have to exit the Aurora and start it again.

EDIT: I believe it happens because of G Hub that after you open it / PC comes back from sleep it takes control of the mouse and it's settings apply

**Comment by Aytackydln** [comment]
Sadly I've tried to solve this before but couldn't success. I hope someone with better experience can solve this :(

**Comment by Crapy** [comment]
> Sadly I've tried to solve this before but couldn't success. I hope someone with better experience can solve this :(

Do you have any direction into what might cause this issue? As a temporary fix I thought maybe we restart the software when the computer wakes up

**Comment by wu4x** [comment]
I have the same issue, both logitech keyboard and mouse lighting stop working and I cannot interact with the aurora software if it was open before I put the computer to sleep

**Comment by hodgesnb** [comment]
Another thing to check that can break Aurora is if you have accidently set the GHub profile to be desktop _and_ persistent.  If you have the persistent profile Aurora can't interact with it. 

You can check this in the settings for your keyboard > Lightsync panel - you want it to not have the lock icon.

**Comment by Crapy** [comment]
> Can you try with v77? I've integrated DarthAffee's RGB.NET.Logitech library. You should use it instead of old Logitech controller.

Doesn't seem to happen anymore
