### ISSUE TITLE
Fatal error to report

### ISSUE THREAD

**Issue by moapatoa** [Aurora-RGB/Aurora#56]
![image](https://user-images.githubusercontent.com/107962128/174908866-3c3c46a2-a263-40a7-9979-456d3557d90a.png)

**Comment by Aytackydln** [comment]
Does this happen often? You didn't give me any info

**Comment by moapatoa** [comment]
Sorry ^^ I just saw "Please report the follow to author", then I reported...

If you wanna have more details, I think the problem came from my PC.
Actually, I had issues with WMI since I tinkered a RGB keybord (it was before trying Aurora). When I installed Aurora and launched it, I get this error. I tryed several times, it was always the same.
Then I repaired my WMI tonight ; and now Aurora launch properly.

I hope this could help you a bit ; if you have any question about this issue I had, don't hesitate, it would be a pleasure if I could help in this great job you have done.

Regards

**Comment by Aytackydln** [comment]
Well, seems like this is not something to fix in Aurora :)
