### ISSUE TITLE
System.Runtime.InteropServices.ExternalException: A generic error occurred in GDI+

### ISSUE THREAD

**Issue by fevieira27** [Aurora-RGB/Aurora#57]
### Actual Behaviour
Every once in a while, I get a popup message with the error from this issue's title. I have only installed Aurora yesterday, so it might be that I'm either doing something wrong or my Clevo laptop is not configured correctly, so that's why I'm opening this issue trying to seek help on what the problem might be. 
[2022-06-22 18.34.09.log](https://github.com/Aurora-RGB/Aurora/files/8961458/2022-06-22.18.34.09.log)

### Reproduction steps and Frequency
Unfortunately, I have not yet figured out a way to reproduce the error. It seems random at the moment.

### Aurora Version:
Latest stable (v54)

### Previously an Issue?
Don't know, as only installed it yesterday evening and had the same error around 3 times since.

**Comment by Aytackydln** [comment]
Looking at the log it seems this is related to Clevo controller code in Aurora. I will check it later today
