### ISSUE TITLE
Add Final Fantasy 14?

### ISSUE THREAD

**Issue by SlytherinGurl77** [Aurora-RGB/Aurora#58]
Game Name: Final Fantasy 14

Methods: I know this game recently got lighting support for Logitech G, but I'm not sure if it can be integrated into Aurora some how. If possible I would like to see it used in Aurora seeing as I have mostly Corsair products.

**Comment by Aytackydln** [comment]
Have you checked existing mods for razer products? If so aurora can capture that key information and display on your devices.

**Comment by SlytherinGurl77** [comment]
I didn't even know those were a thing! Thank you!
