### ISSUE TITLE
Minecraft stuck in Keybind mode

### ISSUE THREAD

**Issue by MercAngel** [Aurora-RGB/Aurora#59]
### Expected Behaviour
Exit keybind mode

### Actual Behaviour
Minecraft does not exit from Keybind mode when you exit the keybind screen have to go into the Aurora App and reset the Controls Assistant Layer by hand V55 looks like it broke at V41 

### Reproduction steps
just go to keybind screen in minecraft

all 3 version plugin from the app forge 1.12.2, 1.13.2, and 1.14.4 useing same version of minecraft

also the version for 1.18.2 i am working on.

### Frequency
Every time

### Aurora Version:
all version from v41 - v55
### Previously an Issue?
v1-v38 work fine

**Comment by Aytackydln** [comment]
What launcher are you using? I couldn't make the mod work for me in any versions

**Comment by MercAngel** [comment]
just the normal one but you have to have forge install 

https://files.minecraftforge.net/net/minecraftforge/forge/index_1.12.2.html
https://files.minecraftforge.net/net/minecraftforge/forge/index_1.13.2.html
https://files.minecraftforge.net/net/minecraftforge/forge/index_1.14.4.html
