### ISSUE TITLE
Choosing solid color layer causes bug

### ISSUE THREAD

**Issue by middleagedman** [Aurora-RGB/Aurora#60]
Brand new default install.  No configuration or changes.

If I click on "Add" to a new layer, and then choose layer type "Solid Color", I immediately get a popup dialog box that says "Error while updating light effects: Object reference not set to an instance of an object"

Keyboard: razer tenkeyless
Windows 11

**Comment by Aytackydln** [comment]
Thanks, I'm aware of this and already solved it. Hopefully I will push my changes with many other fixes
