### ISSUE TITLE
Voron's script 

### ISSUE THREAD

**Issue by AKBoy14** [Aurora-RGB/Aurora#61]
Hi, I bought a K100 the other day, and it seems that for me to use a layer for that keyboard, I need the latest version of this build. The problem is that for some reason, the latest version of this build, don't play well with Voron's script. I use it to monitor my CGU, GPU and Ping, but the ping script just doesn't show with the latest version, but if I download the V26, it shows and it works as intended. Just wondering why that is. Thanks.

**Comment by Aytackydln** [comment]
I'm not too familiar with community content of Aurora. Can you provide me with some links?

Also if you realized exactly which version broke it can you tell me?

**Comment by AKBoy14** [comment]
Hi, this is the link for the Voron Scripts https://github.com/VoronFX/Aurora . As you can see, he hasn't updated since 2017 so that's the latest version of the scripts. I'm gonna add some pictures of how it looks on my end

In the V30, I can see the 4 scripts I normally see with the vanilla Aurora

![V30](https://user-images.githubusercontent.com/27347178/179126454-9fa051af-a8a1-4486-9438-f8de6a2f80c9.JPG)
![V30 Scripts](https://user-images.githubusercontent.com/27347178/179126457-0a3446db-920a-46a5-82b0-92391dbb235a.JPG)

If I go to V35, I lose one of the scripts, showing only 3

![V35](https://user-images.githubusercontent.com/27347178/179126513-f135fc56-f5e5-41b1-b620-97e6b6a904b0.JPG)
![V35 Sccripts](https://user-images.githubusercontent.com/27347178/179126517-cc8ad586-c21f-4b02-a7df-a2e6bcd2415d.JPG)

and everything after that, It only shows me 2 of the Scripts 



![V58](https://user-images.githubusercontent.com/27347178/179126565-5a78d2e5-71f4-4e01-90b2-4358c7223559.JPG)
![V58 Scripts](https://user-images.githubusercontent.com/27347178/179126566-749e1f2d-f4cd-4817-a42c-7e1d3a599982.JPG)


I don't know why some of then works and other don't... And since I don't know anything about scripting. I can't reverse engineer it to make it work with the new version.

**Comment by AKBoy14** [comment]
any update on this?

**Comment by Aytackydln** [comment]
not yet. Last update was important because any people couldnt launch aurora, so I just pushed quick fixes

**Comment by Aytackydln** [comment]
[Vorons.zip](https://github.com/Aurora-RGB/Aurora/files/9285449/Vorons.zip)

Scripts need update because of some naming changes in aurora itself.

Also I don't think gpuLoad and cpuLoad scripts are from voron's?

**Comment by AKBoy14** [comment]
I see, I believe that the gpuLoad and cpuLoad scripts are from an older version, I believe there were 4 once but he combine the CPU and GPU into only one script. But since it's been years since he updated the scripts, my best guess is that I ran out of luck.

**Comment by Aytackydln** [comment]
I updated and shared them on my post above :)

**Comment by AKBoy14** [comment]
You good sir, are the best. I tip my hat to you. Thank you very much

**Comment by VoronFX** [comment]
Hello there. I've published these changes as new script version [vscripts-v1.0-beta.9.zip](https://github.com/VoronFX/Aurora/releases/download/vscripts-v1.0-beta.9/vscripts-v1.0-beta.9.zip).

@Aytackydln Thank you for handling this as I am not actively watching the project.

And yes gpuLoad and cpuLoad are very old ones and are fully covered by PerfEffect script
