### ISSUE TITLE
Blackout away effect not working correctly since v58

### ISSUE THREAD

**Issue by azumukupoe** [Aurora-RGB/Aurora#62]
### Expected Behaviour

Blackout effect completely turns off the lights
### Actual Behaviour

Blackout effect leaves lights slightly lit
### Frequency

Every time
### Aurora Version:

v58
### Previously an Issue?

No

![image](https://user-images.githubusercontent.com/31339007/179434475-8a898d70-bb93-4edb-a297-9b7ffbb440f6.png)

**Comment by Aytackydln** [comment]
Hi, can you show me exactly where do you enable this setting? I am familiar with all of aurora's features :D

**Comment by Aytackydln** [comment]
Trying to understand this better, what are your devices behave this way? How are you connecting to them?

**Comment by Aytackydln** [comment]
really weird... I'm also HyperX Elite 2 on openrgb. Can you share me your profile?

**Comment by Aytackydln** [comment]
Fixed on latest release
