### ISSUE TITLE
Aurora won't launch.

### ISSUE THREAD

**Issue by igorok47** [Aurora-RGB/Aurora#63]
### Expected Behaviour

Aurora should launch after clicking in the desktop shortcut.
### Actual Behaviour

The aurora process starts but it stops before opening any window.
### Reproduction steps

Just double click the shortcut or the executable.
### Frequency

Always.
### Aurora Version:

v58 release.
### Previously an Issue?

Yes, I tried with the v55 release, and got the same result.

Don't know if it matters, but, just in case, the log seems to indicate my OS is a Windows 10 pro. Whereas it actually is a Windows 11 Pro 21H2.

I have just switched today from a failing logitech g810 to a razer huntsman V2. I had (and still have) the logitech gaming software installed and just installed the Razer Synapse. Both seem to recognize Aurora. I installed Aurora for the first time ever in order to get some logitech only integrations to work with the razer keyboard.

[2022-07-27 19.35.59.log](https://github.com/Aurora-RGB/Aurora/files/9201411/2022-07-27.19.35.59.log)

**Comment by Aytackydln** [comment]
probably same as #50

**Comment by logix247** [comment]
I've got the same issue - event log in windows: 

Toepassing: Aurora.exe
Framework-versie: v4.0.30319
Beschrijving: het proces is beëindigd als gevolg van een onverwerkte uitzondering.
Uitzonderingsinformatie: System.AccessViolationException
   bij SBAuroraReactive.LEDManager.EnumConnectedDevices()
   bij Aurora.Devices.Creative.SoundBlasterXDevice.Initialize()
   bij Aurora.Devices.DeviceManager.RetryAll()
   bij System.Threading.Tasks.Task.Execute()
   bij System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bij System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bij System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   bij System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   bij System.Threading.ThreadPoolWorkQueue.Dispatch()

Naam van toepassing met fout: Aurora.exe, versie: 0.0.0.0, tijdstempel: 0x835c4081
Naam van module met fout: ntdll.dll, versie: 10.0.22621.440, tijdstempel: 0x122ad441
Uitzonderingscode: 0xc0000005
Foutmarge: 0x000000000003c51d
Id van proces met fout: 0x0x7430
Starttijd van toepassing met fout: 0x0x1D8A2BB99F9DF2A
Pad naar toepassing met fout: C:\Program Files\Aurora\Aurora.exe
Pad naar module met fout: C:\WINDOWS\SYSTEM32\ntdll.dll
Rapport-id: ebd6f376-423c-4ab9-82e2-0c606d11b4f7
Volledige pakketnaam met fout: 
Relatieve toepassings-id van pakket met fout:

**Comment by Aytackydln** [comment]
Sadly logs don't say anything about what caused the crash. I will try to add more debugging logs for the next releases and I will notify you when I do so you can try again.

**Comment by UnrealFakes** [comment]
I'm experiencing the same thing, though, I'm actually running Windows 10 Pro (OS Build 19044.1826) and not Windows 11. When I run Aurora, it shows up under the iCue (v4.23.137) software integration section for a brief moment, and then it just disappears.

Been using Aurora for a couple years now, this problem only started occurring a day or two ago :/ I have the Corsair K95 RGB Platinum keyboard, not sure if it matters.

**Comment by Aytackydln** [comment]
Thank you @logix247 for including windows event log.
Everyone can you open "%AppData%\Aurora" Config.json and add "SoundBlasterXDevice" line in DevicesDisabled value array?

```
  "DevicesDisabled": {
    "$type": "System.Collections.ObjectModel.ObservableCollection`1[[System.Type, mscorlib]], System",
    "$values": [
...
      "Aurora.Devices.Creative.SoundBlasterXDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
```

**Comment by UnrealFakes** [comment]
> Thank you @logix247 for including windows event log. Everyone can you open "%AppData%\Aurora" Config.json and add "SoundBlasterXDevice" line in DevicesDisabled value array?
> 
> ```
>   "DevicesDisabled": {
>     "$type": "System.Collections.ObjectModel.ObservableCollection`1[[System.Type, mscorlib]], System",
>     "$values": [
> ...
>       "Aurora.Devices.Creative.SoundBlasterXDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
> ```

Thanks! That fixed it! :D

**Comment by logix247** [comment]
@Aytackydln can conform its fixed - thank you for looking into this.

**Comment by Aytackydln** [comment]
Please try the new version. Soundblaster is now disabled by default. If you can't open Aurora delete %AppData%\Aurora folder and try again
