### ISSUE TITLE
RGB fully disabled

### ISSUE THREAD

**Issue by xVxXPrinceXxVx** [Aurora-RGB/Aurora#64]
### Expected Behaviour
 Aurora should be able to control the rgb of the keyboard

### Actual Behaviour
 When Aurora is activated, the rgb lighting is completally turned off. (Logitech G213)

### Reproduction steps
 The application simply disables the keyboard RGB, and the only way to fix it is not using Aurora at all 

### Frequency
 Everytime 

### Aurora Version:
 V58 

### Previously an Issue?
 Don't know

**Comment by Aytackydln** [comment]
can you share me your screenshot of "Device Manager" tab in aurora? I want to see if your device is detected there. Also, can you try with v55?

**Comment by xVxXPrinceXxVx** [comment]
![Captura de tela 2022-07-30 132011](https://user-images.githubusercontent.com/19231635/181859774-60a29656-1803-4772-9537-e694601a16f9.png)
Tried with v55 and the issue persists, same thing with Artemis as well. Gaming wrappers also don't work.

**Comment by Aytackydln** [comment]
Btw, G213 has zone lighting. Which is not the target device for Aurora. Zoned RGB devices also need sperate layouts.

If openrgb supports your device then I can make a special layout for at least the 5 zones it has.

**Comment by xVxXPrinceXxVx** [comment]
> 

I understand, but despite my device not being fully compatible with Aurora isn't it suppose to work even with its limitations?

**Comment by Aytackydln** [comment]
I think it should but device detection is implemented in Logitech SDK that Aurora uses, which is another library I can't access the codes

**Comment by venom2284** [comment]
I to have the G213 and experience this, the layout is in Aurora but we can't use it for rgb which sucks. What can we use?

**Comment by Aytackydln** [comment]
Hi, I looked at the code history and the support trough GHUB SDK has been removed but I don't know the reason. I found a working solution that you can use with OpenRGB. I will be making the release hopefully tomorrow.

**Comment by Aytackydln** [comment]
Hello, I've added a layout that can work with OpenRGB. Sadly I can't add support trough Logitech SDK. I suggest using with OpenRGB for now.
