### ISSUE TITLE
Star Fall away effect removes secondary color after each effect

### ISSUE THREAD

**Issue by AttemptsAtFlight** [Aurora-RGB/Aurora#67]
### Expected Behaviour
Star Fall should light up a random spot with the primary color, then go back to the background color

### Actual Behaviour
After the primary color animation ends, the spot doesn't return to the secondary color but rather the lighting profile

### Reproduction steps
Select Star Fall in away effects

### Frequency
Always

### Aurora Version:
V63

### Previously an Issue?
Last version used was V49 which did not have this issue, unsure which version introduced it

https://user-images.githubusercontent.com/111564554/185575029-5d9483d8-e1fc-4715-9f65-b1c68f004cf6.mp4

**Comment by Aytackydln** [comment]
hello, can you check if this is still the case in V64? I can't reproduce on version 64

**Comment by Aytackydln** [comment]
Never mind, I misunderstood what was supposed to happen. Fixed it and it will come with next update
