### ISSUE TITLE
self updater not working

### ISSUE THREAD

**Issue by azumukupoe** [Aurora-RGB/Aurora#68]
[2022-08-29 14.50.12.log](https://github.com/Aurora-RGB/Aurora/files/9441877/2022-08-29.14.50.12.log)
### Reproduction steps

start aurora, doesn't seem to be checking updates
press the Check for Updates button, no dialog pops up
![image](https://user-images.githubusercontent.com/31339007/187132151-46aad27a-2e6e-4c8b-8f9c-e2630ffb15e5.png)
### Frequency

every time
### Aurora Version:

v65
### Previously an Issue?

yes, since a few versions back

**Comment by Aytackydln** [comment]
Thanks for reporting. I would not notice this since I don't use updater myself. Found the problem, fix is coming next update

**Comment by snappyapple632** [comment]
As far as I'm concerned the self updater still isn't working as of v69.
