### ISSUE TITLE
App hangs after RDP connection

### ISSUE THREAD

**Issue by voed** [Aurora-RGB/Aurora#70]
The app just completely freezes after connecting to RDP session. I cannot interact with window or system tray icon and numlock layer is blinking. Killing process and starting again fixes the issue.
### Reproduction steps
1. Start Aurora on PC1
2. Connect to PC1 from PC2 via RDP
3. Disconnect and get back to PC1

### Frequency
Every time

### Aurora Version:
v59

### Previously an Issue?
Not sure, but i think yes

Logs:
```[INFO] 16:31:34: 
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Executing Directory: C:\Program Files\Aurora
Launch Directory: C:\Program Files\Aurora
Processor Count: 24
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: v59
========================================
 
[INFO] 16:31:34: Loading devices from assembly... 
[INFO] 16:31:34: [ASUS] Could not find Asus Aura SDK, please install version v1.07.71 
[INFO] 16:31:34: Loading Configuration 
[INFO] 16:31:34: Loading Plugins 
[INFO] 16:31:34: Loading KB Layouts 
[INFO] 16:31:34: Loading Input Hooking 
[INFO] 16:31:34: Loading RazerSdkManager 
[WARN] 16:31:34: Currently installed razer sdk version "0.0.0" is not supported by the RazerSdkManager! 
[INFO] 16:31:34: Loading Applications 
[INFO] 16:31:37: Fetching latest pointers 
[INFO] 16:31:37: Loading Device Manager 
[INFO] 16:31:37: [Device][Logitech] Trying to initialize Logitech using the dll for GHUB 
[INFO] 16:31:37: [Device][Logitech] Initialized Successfully. 
[INFO] 16:31:37: [Device][Wooting] Initialized Successfully. 
[INFO] 16:31:37: Starting GameStateListener 
[INFO] 16:31:37: Listening for game integration calls... 
[INFO] 16:31:37: Loading ResourceDictionaries... 
[INFO] 16:31:37: [IPCServer] Pipe created 44736323 
[INFO] 16:31:37: [AuroraCommandsServerIPC] Pipe created 5828284 
[INFO] 16:31:37: Loaded ResourceDictionaries 
[INFO] 16:31:37: Loading ConfigUI... 
[WARN] 16:31:38: Could not find an AutoNode getter method for field '_ParsedData' of type 'JObject'. It will not be automatically populated. 
```

**Comment by voed** [comment]
Updated to v65, problem still exists

**Comment by Aytackydln** [comment]
hmm can you share windows event logs related to aurora?

**Comment by voed** [comment]
![image](https://user-images.githubusercontent.com/10352360/187998467-8f4074e9-8f13-4855-b170-97e5d2069e9a.png)

Here's what i got upon killing aurora task. Tried multiple times, stack trace was the same

**Comment by voed** [comment]
I guess the problem is TaskbarNotification lib which was not updated for almost 10 years. 
Maybe use this lib instead? https://github.com/HavenDV/H.NotifyIcon

**Comment by Aytackydln** [comment]
Yes, I was thinking of replacing it. Some other people have crashes because
of it, too

**Comment by Aytackydln** [comment]
Sadly that library doesn't work on Aurora. Only thing I could do is increase the version from 1.0.5 to 1.1.0

**Comment by voed** [comment]
> Sadly that library doesn't work on Aurora. 
Why not? Works fine, does not crash anymore. Created PR. 
But NumLock layer keeps blinking.

**Comment by Aytackydln** [comment]
Thanks for the PR. That was exactly what I did though. I will try tomorrow
