### ISSUE TITLE
Can we change the mode set when closing Aurora?

### ISSUE THREAD

**Issue by Trihy** [Aurora-RGB/Aurora#71]
I´d noticed when closing Aurora, at least for asus devices, leds goes back to maximum brightness and rainbow effect? Not sure how that is set, but would be great to have a way to set this, or at least go back to the latest mode set by Aura Sync/Armoury before opening Aurora. Maybe aurora could check which mode is set when launching and setting the same when closing it?

**Comment by Aytackydln** [comment]
Can you check the current behavior?

**Comment by Trihy** [comment]
> Can you check the current behavior?

Hi. Tried on aurora v95. When closing it, flash for a second the latest mode set on aura sync, then stay off. If I open Aura sync, I have to turn lights on again, since on/off switch seems to change to off when closing Aurora.

Not bad for me. Before it was all led at maximum brightness when closing Aurora.

**Comment by Aytackydln** [comment]
Alright, this now the issue of RGB.NET library. The library doesn't expose anything about closing modes. You should make an issue at [RGB.NET](https://github.com/DarthAffe/RGB.NET) if you want this changed (will also change for Artemis)
