### ISSUE TITLE
Logitech G910 has broken keys with OpenRGB

### ISSUE THREAD

**Issue by wfowler1** [Aurora-RGB/Aurora#72]
Cross-posting this from the old repo so it's in the right repository.

### Expected Behaviour

When using the Logitech G910 with OpenRGB, the keys ought to all work properly.

### Actual Behaviour

The G6, G7, G8, G9 keys and the "G910" logo aren't mapped and instead fall under "Peripheral logo" if the option is set in the OpenRGB options.

### Reproduction steps

1. Use Logitech G910 keyboard with Aurora and OpenRGB.
2. Observe the OpenRGB and keyboard do not use the G6-G9 keys or G910 logo properly.

Aurora screenshot, showing correct colors:
![image](https://user-images.githubusercontent.com/5846565/188282846-0eacc99a-dd96-4ed7-82b5-95dd019c51c8.png)

OpenRGB screenshot, showing actual colors:
![image](https://user-images.githubusercontent.com/5846565/188282861-824e44b3-9c48-4fcf-ab8e-26e3be8579de.png)

### Frequency

100%

### Aurora Version:

v63

### Previously an Issue?

Don't know

**Comment by wfowler1** [comment]
You said:
> OpenRGB doesn't include additional light mappings. This keyboard will need custom layout for openrgb. I can make it myself after changing some implementation of additional light mappings of keyboards.

I'm a programmer, is this something I can help with? If you point me in the right direction as to what files I could look in, I can experiment.

**Comment by Aytackydln** [comment]
Yes! Those keys without names will be mapped as AdditionalLight# keys. You can check their enum ordinals from OpenRGBKeyNames and experiment which one is which. Tag properties in json files are the neum ordinals

https://github.com/Aurora-RGB/Aurora/blob/master/Project-Aurora/Project-Aurora/kb_layouts/logitech_g910.json
https://github.com/Aurora-RGB/Aurora/blob/master/Project-Aurora/Project-Aurora/Devices/OpenRGB/OpenRGBKeyNames.cs
