### ISSUE TITLE
OpenRGB + Asus MB & GPU

### ISSUE THREAD

**Issue by MichaelDavidGK** [Aurora-RGB/Aurora#76]
### Expected Behaviour

Asus Motherboard and GPU shouldn't be loaded via OpenRGB

### Actual Behaviour

Asus Motherboard and GPU via OpenRGB are treated as mouse

### Reproduction steps

Use Asus MB or GPU with OpenRGB

### Frequency

Whole the time

### Aurora Version:

v65

### Previously an Issue?

Unknown

![image](https://user-images.githubusercontent.com/39009683/188898682-217c98c9-9964-425d-ae51-43720b2d91c4.png)

**Comment by Aytackydln** [comment]
"Use peripheral logo for unknown leds" option is on by default. You can turn that off/restart connection and your mobo and gpu lights will be mapped as additional lights

GPU and mobo will share some of the additional lights tho. I'm planning to make a fix for that later

**Comment by MichaelDavidGK** [comment]
well it works, but wouldn't it be better to add check for it, like ability to disable management of selected peripherals from Openrgb (it would stay managed by Openrgb instead of Aurora then)
Also additional lights (debug) would be nicer as additional device instead of being in preferred keyboard (since u r fixing them not being together then this might be a good thing to add too)
Adding option to edit keyboard layout would be nice as well since some are 60/65/75 and more custom

**Comment by Aytackydln** [comment]
Aurora is focused on "desktop" lights. If you want more freedom I suggest you try [Artemis-RGB](https://github.com/Artemis-RGB/Artemis).

It's downside is it's much more complicated and some stuff are handled by plugins which you have to search them from the wiki and the discord server.

**Comment by MichaelDavidGK** [comment]
I knew about Artemis, but unfortunately it is a complete mess rn
thanks anyway
