### ISSUE TITLE
Support for Glorious mouses

### ISSUE THREAD

**Issue by MichaelDavidGK** [Aurora-RGB/Aurora#77]
Please add support for the following device:

**Device Name:**  Glorious Model D/D- & O/O-

**Device Website:**  https://www.gloriousgaming.com/

OpenRGB supports them so shouldn't be hard to add them via it

If they are already functional then this might be related to [https://github.com/Aurora-RGB/Aurora/issues/76](url) since motherboard and GPU are seen as mouse and mouse isn't seen at all

**Comment by MichaelDavidGK** [comment]
![image](https://user-images.githubusercontent.com/39009683/189195207-de03b856-a71c-4671-9c56-17d5af883dd4.png)

**Comment by Aytackydln** [comment]
Did you try other layouts? Also openrgb needs to support "direct mode" on your mouse. I see "static mode" in screenshot

**Comment by MichaelDavidGK** [comment]
It doesn't support Direct mode :(
