### ISSUE TITLE
Add support for Sharkoon Skiller SGK3 MECH

### ISSUE THREAD

**Issue by coinkillerl** [Aurora-RGB/Aurora#78]
Device name : Sharkoon Skiller SGK3 MECH
Website : https://en.sharkoon.com/product/SKILLER+MECH+SGK3

**Comment by Aytackydln** [comment]
Sorry for late response. Implementing this brand's RGB into Aurora is currently not possible and not worth the time even if it did.

It's best to spend the effort into integrating it into [Openrgb](https://gitlab.com/CalcProgrammer1/OpenRGB/-/issues) then it can be used with other softwares too
