### ISSUE TITLE
Sound BlasterX Device Support

### ISSUE THREAD

**Issue by OCFormula** [Aurora-RGB/Aurora#80]
I was using these devices, but it's a shame that they're missing from v68 (Sound BlasterX Vanguard K08)

Device Name: 
Sound BlasterX Vanguard K08 
Sound BlasterX Kratos S5

Device Website: 
https://sg.creative.com/p/archived-products/sound-blasterx-vanguard-k08
https://sg.creative.com/p/archived-products/sound-blasterx-kratos-s5

**Comment by Aytackydln** [comment]
okay, I will add the library again by compiling it myself. Hopefully this time it won't have any problems
Might take a few days

**Comment by Aytackydln** [comment]
Hi, can I send you a test build for you to try it?

**Comment by OCFormula** [comment]
yes, please send it OCFormula@protonmail.com

**Comment by Aytackydln** [comment]
sent it, btw

**Comment by OCFormula** [comment]
![화면 캡처 2023-01-04 160242](https://user-images.githubusercontent.com/105538842/210501318-92c454fb-7795-435b-b0eb-321e9076649d.png)
The keyboard is recognized, but the lights don't seem to work.

**Comment by Aytackydln** [comment]
I see, that's okay. I will fix it and release it next build. Thanks

**Comment by Aytackydln** [comment]
can you check https://github.com/Aurora-RGB/Aurora/releases/tag/v106

**Comment by OCFormula** [comment]
The lighting works well. Thank you.
