### ISSUE TITLE
Error occurred after using 'Disable Device Control', CPU Usage issue and Overwatch's lighting functionality does not working

### ISSUE THREAD

**Issue by OCFormula** [Aurora-RGB/Aurora#81]
After using 'Disable Device Control', the lighting function should be activated normally when the overwatch is executed and entered the training ground, but it was not

### Aurora Version:
v72

### Previously an Issue?
No

[2022-09-19 16.34.31.log](https://github.com/Aurora-RGB/Aurora/files/9596956/2022-09-19.16.34.31.log)
[2022-09-19 16.21.33.log](https://github.com/Aurora-RGB/Aurora/files/9596957/2022-09-19.16.21.33.log)
<img width="1044" alt="화면 캡처 2022-09-19 163330" src="https://user-images.githubusercontent.com/105538842/190970929-143beb94-cc1a-46bc-a53d-2e62c666f938.png">

**Comment by Aytackydln** [comment]
Hmm, this error shouldn't be related to "Disable Device Control". Do you have "Enable Post Process" in your chroma layer in Overwatch profile?

**Comment by OCFormula** [comment]
> 
Yes. I always turned on 'Enable Color Post Process' and set 'Brightness Change' to 0.500 and used it

**Comment by Aytackydln** [comment]
Last update I changed color creation methods to "unsafe" way. This causes incorrect colors to have wrong colors instead of throwing error. Do you notice wrong colors now?

**Comment by OCFormula** [comment]
I can't really feel the difference between the colors that are displayed after the update and the previous colors.
I will install the previous version soon and check the difference in color.
And the error no longer occurs.

And the problem with CPU Usage of Razer Synapse Service seems to have been caused by running OpenRGB and Razer Synapse simultaneously.
When I turned off Razer Synapse and ran only OpenRGB, the problem no longer occurs.

**Comment by Aytackydln** [comment]
If you have razer devices and controlling them with Openrgb you should click "Disable Device Control" button in devices & wrappers tab

**Comment by OCFormula** [comment]
In current test, since I disabled the "Synapse Service" and tested it, it seems that there was no problem with using OpenRGB and Aurora even though the "Disable Device Control" button was not pressed.

I set "Enable Color Post Process" to 0.500 and compared the colors of v58 and v73, but I don't know much difference with my eyes.
