### ISSUE TITLE
"Aurora-Updater has stopped working" & Device Plugins Not Initializing.

### ISSUE THREAD

**Issue by Benjamoose** [Aurora-RGB/Aurora#82]
### Expected Behaviour
1. The automatic updater starting at launch and updating if necessary.
2. Device plugions not initializing (CoolerMaster, Corsair, etc).

### Actual Behaviour
1. At every program launch, "Aurora-Updater" crashes. The application itself loads normally right afterwards.
2. The plugins in the "Devices" tab wont run. The first time I used the app, multiple were automatically running, presumably for detections, but now none are, and pressing "start" on any of them does nothing.

### Reproduction steps
1. Launch the application.
2. No idea.

### Frequency
Every time.

### Aurora Version:
v65

### Previously an Issue?
1. This is always happened since the first time I tried using the program a few weeks ago.
2. Not sure. The plugins thing was fine and working normally until recently. Possibly?

### Screenshots
1. 
![UpdaterCrash](https://user-images.githubusercontent.com/32703517/191413457-108a977e-70a3-49f8-a7fe-3f2589974904.png)

2.
![Devices](https://user-images.githubusercontent.com/32703517/191413462-d9cba516-30b9-4030-9ad5-ad2632f22b69.PNG)

### Logs
[2022-09-20 18.09.51.log](https://github.com/Aurora-RGB/Aurora/files/9612937/2022-09-20.18.09.51.log)

### Specs
**OS:** Windows 10
**GPU:** GTX 1070
**CPU:** i7-4790K
**RAM:** 16GB

**Comment by Aytackydln** [comment]
Updater is fixed in the latest pre-release versions. For cooler master I've updated the sdk dll before. I guess I should revert it

**Comment by Aytackydln** [comment]
Just to be sure, can you try v63 and see if it works?

**Comment by Aytackydln** [comment]
Sorry for late response. I've added RGB.NET implementation in the latest release, can you try it?
https://github.com/Aurora-RGB/Aurora/releases/tag/v87
