### ISSUE TITLE
Roccat Vulcan crashing due to high brightness

### ISSUE THREAD

**Issue by StrykeDev** [Aurora-RGB/Aurora#83]
### Expected Behaviour

When setting the device's color to white it should be white (and not crash)
### Actual Behaviour

When setting the device's color to white it's white with a flickering tint of red, green, and blue.
A possible cause is the applied color is doubled or that the device can't handle all 3 channels at full brightness.
When left like that for a few sec the keyboard crash and reset.
I fixed it by applying a black mask with 50% alpha on the entire keyboard.
### Reproduction steps

1. Get a Roccat Vulcan keyboard
2. Set everything to white
### Frequency

Every time 
### Aurora Version:

v65
### Previously an Issue?

Probably

**Comment by Aytackydln** [comment]
can you share your profile and the layer you change that causes the crash? This is probably a wide range bug

**Comment by StrykeDev** [comment]
> can you share your profile and the layer you change that causes the crash? This is probably a wide range bug

Any layer with white(more than 127 in all ch) color will cause it to crash
Solid color, fill color, ambient, chroma, w/e it's an issue with the driver or the keyboard.
Haven't test it with the official drivers tho, I'll update later.
Btw it also happen when using OpenRGB(directly) and that other fancy Aurora software.

**Comment by Aytackydln** [comment]
I didn't have time to look at this issue previously and issue stayed up for too long. If you want to use aurora again and this issue still happens I can add the rgb.net implementation which should be more stable.

Feel free to reopen the issue
