### ISSUE TITLE
Asus MB (Z270F) doesn't disconnect properly

### ISSUE THREAD

**Issue by StrykeDev** [Aurora-RGB/Aurora#85]
### Expected Behaviour

When closing Aurora or when stopping\disabling the Asus API the motherboard should be released from Aurora's control. 
### Actual Behaviour

It just doesn't release.
Although the GPU (Asus GTX 1080TI O11G) does release properly.
### Reproduction steps

1. Get an Asus Z270F MB
2. Enable and start it
3. Close Aurora or disable or stop it
### Frequency

Every time
### Aurora Version:

v65
### Previously an Issue?

Probably

**Comment by Aytackydln** [comment]
Hi, sorry for late response. Is the unwanted behaviour colors staying as they were at the moment of disconnection?

**Comment by StrykeDev** [comment]
> Hi, sorry for late response. Is the unwanted behaviour colors staying as they were at the moment of disconnection?

Yes... but the thing is that it keep the motherboard under Aurora's control.

**Comment by Aytackydln** [comment]
The colors still update after disconnection?

**Comment by StrykeDev** [comment]
> The colors still update after disconnection?

I think so? Not sure, stopped using it.

**Comment by Aytackydln** [comment]
Aurora implementation is now changed and this behaviour probably changed
