### ISSUE TITLE
Add color correction option per device

### ISSUE THREAD

**Issue by StrykeDev** [Aurora-RGB/Aurora#86]
Not every device is the same, most of them have lousy color accuracy, giving us a color multiplier would be great!
**Motherboards should have another correction option for RGB strips which have the worse color accuracy.**

**Comment by Aytackydln** [comment]
https://github.com/Aurora-RGB/Aurora/releases/tag/v73

can you try the new option here?

**Comment by StrykeDev** [comment]
> https://github.com/Aurora-RGB/Aurora/releases/tag/v73
> 
> can you try the new option here?

I don't see anything related to color correction... (v73)

**Comment by StrykeDev** [comment]
It works perfectly fine, thanks!
