### ISSUE TITLE
ASUS Aura does not work after v65

### ISSUE THREAD

**Issue by joaocaparroz** [Aurora-RGB/Aurora#90]
Asus Aura integration does not work for any version higher than v65.
Tested all versions.
Tested various Asus Aura SDK versions.

When I click `start`, it loads for a few seconds, freezes any animation on aura LEDs and the button backs to `start`.

**Comment by Aytackydln** [comment]
can you send me logs?

**Comment by joaocaparroz** [comment]
[2022-10-12 17.36.06.log](https://github.com/Aurora-RGB/Aurora/files/9768537/2022-10-12.17.36.06.log)

**Comment by Aytackydln** [comment]
btw, I suggest using openrgb for controlling aura devices unless you are using led mappings for aurora

**Comment by joaocaparroz** [comment]
> btw, I suggest using openrgb for controlling aura devices unless you are using led mappings for aurora

I agree and it works, but I'm used to use led mappings.
