### ISSUE TITLE
Solid fill layer does not work until edited

### ISSUE THREAD

**Issue by joaocaparroz** [Aurora-RGB/Aurora#91]
### Expected Behaviour
Solid Fill Layer works filling all leds with the same color

### Actual Behaviour
Solid Fill Layer does not work until you select a new color

### Reproduction steps
Created a "background" solid fill layer for desktop

### Frequency
This happens everytime Aurora starts

### Aurora Version:
v73

### Previously an Issue?
I think this is happening after v65

![image](https://user-images.githubusercontent.com/19500222/195443714-176e0bfa-26f5-41ae-8a41-6c67353402b4.png)

**Comment by Aytackydln** [comment]
Fixed with v74. I only had time for this fix today
