### ISSUE TITLE
Aurora crashes suddenly

### ISSUE THREAD

**Issue by joaocaparroz** [Aurora-RGB/Aurora#92]
### Expected Behaviour
Aurora functions normally

### Actual Behaviour
Aurora crashes after a few seconds or minutes
![image](https://user-images.githubusercontent.com/19500222/196275639-10cd71dd-4f70-4e66-8f76-a075d7ab5020.png)
![image](https://user-images.githubusercontent.com/19500222/196275752-6bac721d-20fc-42b6-a623-08c35955ec92.png)

### Reproduction steps
Open Aurora, wait

### Frequency
Everytime, after a few seconds or minutes (it varies)
### Aurora Version:
v75

### Previously an Issue?
No

[2022-10-17 20.23.31.log](https://github.com/Aurora-RGB/Aurora/files/9804277/2022-10-17.20.23.31.log)

**Comment by joaocaparroz** [comment]
This only happens if General Settings -> Device Manager -> Asus is running.

**Comment by Aytackydln** [comment]
Can you copy this file as AuraServiceLib.dll to your Aurora folder and try again?
https://github.com/Aurora-RGB/Aurora/blob/v65/Project-Aurora/Project-Aurora/Interop.AuraServiceLib.dll

**Comment by Aytackydln** [comment]
Also another option is using armory crate or newest aura sync with the original dll. Whatever works better

**Comment by Aytackydln** [comment]
I reverted the aura sdk library update:
https://github.com/Aurora-RGB/Aurora/releases/tag/v76

**Comment by joaocaparroz** [comment]
The problem persists after updating to v76.

**Comment by Aytackydln** [comment]
I've fully reverted asus changes this time. Check v77 please

**Comment by joaocaparroz** [comment]
The problem persists after updating to v77.

**Comment by Aytackydln** [comment]
Alright, I will give up on razer's aura library. I will integrate RGB.NET.Devices.Asus later. Should be easy after implementing the Logitech library

**Comment by Aytackydln** [comment]
[win10-x64.zip](https://github.com/Aurora-RGB/Aurora/files/9998176/win10-x64.zip)

I've implemented RGB.NET's asus library, also changed device mapping system to handle RGB.NET instead of only Asus devices. Can you unzip this OVER your own Aurora and try it?

Also make a copy of your %appdata%/Aurora folder just in case

**Comment by joaocaparroz** [comment]
It works perfectly! I just had to set all Asus leds as something (logo led in my case) in "Configure Asus Peripheral Devices".

Thanks!

**Comment by Aytackydln** [comment]
https://github.com/Aurora-RGB/Aurora/releases/tag/v81

new implementation is now with the latest release
