### ISSUE TITLE
Elite Dangerous - Odyssey

### ISSUE THREAD

**Issue by Madproforg** [Aurora-RGB/Aurora#94]
The odyssey expansion for Elite Dangerous changes the format for the Startpreset.start file.
The non expansion version is a single line (still works fine  with Aurora), while Odyssey is now 4 lines so tries to open a file with an  invalid name
e.g.
file\n\rfile\n\rfile\n\rfile.binds

Looking through the code found this
Aurora/Project-Aurora/Project-Aurora/Profiles/EliteDangerous/GameEvent_EliteDangerous.cs
line 204
string currentBindPrefix = File.ReadAllText(EliteConfig.BINDINGS_PRESET_FILE).Trim();

if it's changed to only read the first line rather than the whole file it should stop the error.

**Comment by NightHammer1000** [comment]
Still not totaly fixed. Aurora Crashes frequently with a JSON Additional Text Detected Error while parsing the Journal.
