### ISSUE TITLE
Uncharted: Legacy of Thieves Support

### ISSUE THREAD

**Issue by mechcentric** [Aurora-RGB/Aurora#96]
Wondering if support will be added for this game. Thanks!

**Comment by Aytackydln** [comment]
Sadly we don't have people that can add game integration support without the game having modding support. Well... currently only I am maintaining this project. I should pin a message saying game requests mostly won't have an answer.

You can just hope game comes with Razer Chroma support or something similar for now

**Comment by mechcentric** [comment]
It does but on my ducky one 2 rgb it only has 4 zones. Aurora does not have this issue using the chroma sdk. I use Aurora for rotrr, which has chroma support not does not work with my board via synapse for some reason. I guess I was just hoping Aurora could do one better.

**Comment by Aytackydln** [comment]
can you try other layouts with 4 zones?

**Comment by mechcentric** [comment]
> can you try other layouts with 4 zones?

Not sure what you mean by this. As in other keyboards with different layouts?

**Comment by Aytackydln** [comment]
Are you able to use your keyboard with aurora at all?

**Comment by Aytackydln** [comment]
With 4 zones keyboards, like Logitech G213, my solution was getting the color average for key colors. You can look at them in "Preffered Keyboard" in aurora settings. But, your keyboard won't work with 4 zone layouts if you are using ducky connector. It might work with openrgb though

**Comment by mechcentric** [comment]
> Are you able to use your keyboard with aurora at all?

It works well with Aurora desktop profiles and supported games. No 4 zone bs except with ducky connect and razer synapse. OpenRGB seems only able to do entire board or per key direct lighting.

**Comment by Aytackydln** [comment]
https://openrgb.org/devices.html your keyboard is listed here. Can you show me the led view in openrgb?

**Comment by mechcentric** [comment]
![image](https://user-images.githubusercontent.com/45723202/198841003-c48a1e88-3e5c-421e-a6f5-6587bad55e39.png)

**Comment by Aytackydln** [comment]
So, openrgb shows per-key lightning even though it has 4 zone lighting?

**Comment by mechcentric** [comment]
that's correct. 4 zone is a razer connect limitation for the board, not a limitation of the board itself. essentially, razer is pulling shenanigans.

**Comment by Aytackydln** [comment]
I know about the 4 zone thing but it applies to additional peripheral stuff. Maybe razer sdk thinks your keyboard such way. Can you click the "Disable Device Control" in Aurora's Wrapper Settings tab ?

**Comment by Aytackydln** [comment]
Should work with Chroma integration
