### ISSUE TITLE
the light of FN key on G PRO X is not functioning

### ISSUE THREAD

**Issue by RoyLiu04** [Aurora-RGB/Aurora#98]
### Actual Behaviour
The FN key on G PRO X keyboard can not  be set by Aurora, but if I change the keyboard model from GPRO to G810, the FN key is correctly controlled

### Aurora Version:
v77

**Comment by Aytackydln** [comment]
Which device controller are you using? Logitech, Logitech RGB.NET or OpenRGB?

**Comment by RoyLiu04** [comment]
I’m using Logitech. 在 2022年11月11日，01:26，Aytaç Kayadelen ***@***.***> 写道：﻿
Which device controller are you using? Logitech, Logitech RGB.NET or OpenRGB?

**Comment by Aytackydln** [comment]
Can you try the new Logitech (RGB.NET) controller? If it still doesn't work there you can remap it with the new feature. And then you can tell me which key it was and I can fix it in the layout

**Comment by RoyLiu04** [comment]
I clicked the START button of Logitech(RGB.NET) but nothing happened. Do I have to do something to initialize this function?

**Comment by RoyLiu04** [comment]
I can provide a possible solution:

in kb_layouts/logitech_gpro.json, there are lines:
`    "99": {
      "visualName": "FN",
      "tag": 107,
      "line_break": null,
      "margin_left": null,
      "margin_top": null,
      "width": null,
      "height": null,
      "font_size": null,
      "width_bits": null,
      "height_bits": null,
      "margin_left_bits": null,
      "margin_top_bits": null,
      "enabled": null
    }`
maybe change the tag to 99 from 107 can solve the problem?

**Comment by RoyLiu04** [comment]
> I can provide a possible solution:
> 
> in kb_layouts/logitech_gpro.json, there are lines: ` "99": { "visualName": "FN", "tag": 107, "line_break": null, "margin_left": null, "margin_top": null, "width": null, "height": null, "font_size": null, "width_bits": null, "height_bits": null, "margin_left_bits": null, "margin_top_bits": null, "enabled": null }` after I change the tag to 99 from 107 the problem is solved

this only soved the problem when using logitech as controller. Seems like the GHUB treats this FN key as right windows key?

When using OPENRGB controller, AURORA cannot send RGB value of the key 99 to OPENRGB, I tried change the value back to 107 but still doesn't work. The OPENRGB provide RGB mapping including lock indicators, game mode button and light button, hope AURORA can add these too.

**Comment by Aytackydln** [comment]
To find correct OpenRGB led number open your keyboard in LED View in OpenRGB. Note the name for FN key and find the corresponding KeyName in this file:
https://github.com/Aurora-RGB/Aurora/blob/master/Project-Aurora/Project-Aurora/Devices/OpenRGB/OpenRGBKeyNames.cs

Then the number is the corresponding number of that KeyName here:
https://github.com/Aurora-RGB/Aurora/blob/master/Project-Aurora/Project-Aurora/Devices/DeviceKeys.cs

**Comment by RoyLiu04** [comment]
In openrgb the key name is shown as FN key. In the layout file of openrgb (not the layout file of Aurora), the FN key is actually the right FN. So in file OpenRGBKeyNames.cs, there is "Key: Right Fn", DK.FN_Key. 
And FN_Key value is 107. 
But default Aurora setting does not work, in which the value is 107.

**Comment by Aytackydln** [comment]
Key name needs to be exact match. If it is FN in openrgb, key name must be etiher "Key: FN" or "FN" in OpenRGBKeyNames file, and has to match letter cases. Adding { "Key: FN"         , DK.FN_Key                 }, should solve it.

**Comment by RoyLiu04** [comment]
Can I change this at my computer? I can't find the cs file to modify. In the OPENRGB the key name is displayed as "Key: Fn". Please consider add this in the .cs file. Thanks!

**Comment by Aytackydln** [comment]
I changed that part. Will be in the next release

**Comment by Aytackydln** [comment]
Can you check this in the last release:
https://github.com/Aurora-RGB/Aurora/releases/tag/v87

**Comment by RoyLiu04** [comment]
In the latset version of OpenRGB, the FN key is displayed as "Key: Right Fn". So in Aurora v84, the problem is fixed. Key value need to be 107 in order to work with OpenRGB. And 99 to work with Logitech G HUB. Thanks for your work!
