### ISSUE TITLE
Possible workaround for ambilight mode and DRM content?

### ISSUE THREAD

**Issue by Trihy** [Aurora-RGB/Aurora#99]
Hi. Been using Aurora for ambilight purposes since a long time. But the DRM content was always a problem.

Most streaming platforms and online tv had them.

Even on latest builds of Aurora, enabling ambilight makes Netflix Win10/11 app goes black, no video, just sound. You disable ambilight profile and video goes back. Other platforms keep streaming correctly but ambilight profile does nothing because of DRM.

But I read that this platforms doesnt care if you take low resolution screenshots.

So, Im wondering if enabling some low res screen cap mode for aurora could solve this problem with DRM. Any 640x480 or maybe even lower will be enough for ambilight on most situations. I read it doesnt care if you do even 1280x720, but not sure.

Thanks for reading.

**Comment by Aytackydln** [comment]
I will look into this. Also, can you try Artemis is it can read DRM content? If it can read I will just use the library it uses

https://github.com/Artemis-RGB/Artemis

**Comment by Trihy** [comment]
> 

Hi. Tried Artemis Ambilight plugin and doesnt work on DRM content.

**Comment by Aytackydln** [comment]
I've looked into this with current libraries but I don't see any parameter for capture resolution. Maybe some more advanced library could do it but I don't know any
